### ISSUE TITLE
error during water calibration

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#124]
I'm trying to run the water calibration on one of my rigs but when I do I get this error message. ```Traceback (most recent call last):
 File "C:\iblrig_params\IBL\tasks\_iblrig_calibration_water\_iblrig_calibration_water.py", line 32, in <module>
   sph = SessionParamHandler(task_settings, user_settings)
 File "C:\iblrig_params\IBL\tasks\_iblrig_calibration_water\session_params.py", line 54, in __init__
   board=self.PYBPOD_BOARD, make=True)
 File "C:\iblrig_params\path_helper.py", line 47, in __init__
   self.VISUAL_STIMULUS_TYPE / 'Gabor2D.bonsai')
 File "c:\users\cshl-behavior-pc2\anaconda3\envs\iblenv\lib\pathlib.py", line 892, in __truediv__
   return self._make_child((key,))
 File "c:\users\cshl-behavior-pc2\anaconda3\envs\iblenv\lib\pathlib.py", line 679, in _make_child
   drv, root, parts = self._parse_args(args)
 File "c:\users\cshl-behavior-pc2\anaconda3\envs\iblenv\lib\pathlib.py", line 633, in _parse_args
   a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType```

**Comment by anne-urai** [comment]
thanks @nbonacchi - if the patch will be later today we can wait a few hours!
