### ISSUE TITLE
Error when I open rig box 

### ISSUE THREAD

**Issue by valagui** [int-brain-lab/iblrig#137]
So as I was training today, I noticed my rig came up with this error whenver I tried to re-adjust the water spout in my rig during training. This immediately happened in one of my rigs. The task stopped and I was presented with these errors :Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_biasedChoiceWorld\_iblrig_tasks_biasedChoiceWorld.py", line 168, in <module>
    trial_data = tph.trial_completed(bpod.session.current_trial.export())
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_biasedChoiceWorld\trial_params.py", line 148, in trial_completed
    assert correct or error or no_go
AssertionError
C:\iblrig_params\IBL\experiments\_iblrig_tasks\setups\biasedChoiceWorld\sessions\201902~1\20190220-172201.csv - The process cannot access the file because it is being used by another process.

Unhandled Exception: System.CannotUnloadAppDomainException: Error while unloading appdomain. (Exception from HRESULT: 0x80131015)
   at System.AppDomain.Unload(AppDomain domain)
   at Bonsai.Program.Main(String[] args)
   at Bonsai64.Program.Main(String[] args)
Connected to https://alyx.internationalbrainlab.org as anneu
2019-02-20 17:50:04.803 INFO     [registration.py:46] creating session for C:\iblrig_data\Subjects\IBL_46\2019-02-19\001
Traceback (most recent call last):
  File "..\..\..\create_session.py", line 33, in <module>
    main()
  File "..\..\..\create_session.py", line 21, in main
    create(IBLRIG_DATA, dry=False)
  File "c:\ibllib\python\alf\one_iblrig.py", line 41, in create
    rc.create_sessions(root_data_folder, dry=dry)
  File "c:\ibllib\python\oneibl\registration.py", line 48, in create_sessions
    status_str = self.register_session(flag_file.parent, file_list=False)
  File "c:\ibllib\python\oneibl\registration.py", line 24, in func_wrapper
    f = func(self, sessionpath, *args, **kwargs)
  File "c:\ibllib\python\oneibl\registration.py", line 119, in register_session
    end_time = start_time + datetime.timedelta(seconds=ses_duration_secs)
OverflowError: date value out of range

**Comment by oliche** [comment]
duplicate https://github.com/int-brain-lab/ibllib/issues/53
