### ISSUE TITLE
_iblrig_calibration doesn't exist in Alyx

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#138]
After the latest update (3.7.3) I cannot connect to alyx. I did sync with alyx on pybpod and I changed ONE file. 
I have same error when I test with ibl_test_user, the calibration was done on that rig and file is saved on local computer.
However still have issue with connecting with alyx and this error. 

```
(base) C:\iblrig>pybpod
Finding pybpod folder...
Activating IBL environment...
Launching pybpod...
libpng warning: iCCP: known incorrect sRGB profile
21/02/2019 01:48:33 | WARNING | 6868 | pyforms_generic_editor.plugins.loader | install_plugins | Plugins path was not defined by user
libpng warning: iCCP: known incorrect sRGB profile
2019-02-21 13:48:51.203 INFO     [path_helper.py:469] NOT FOUND: PREVIOUS_DATA_FILE
2019-02-21 13:48:51.205 WARNING  [path_helper.py:488]
        ##########################################
            NOT FOUND: PREVIOUS_DATA_FILE
        ##########################################
                    USING INIT VALUES
        ##########################################
2019-02-21 13:48:51.205 INFO     [path_helper.py:469] NOT FOUND: PREVIOUS_SETTINGS_FILE
2019-02-21 13:48:51.206 INFO     [path_helper.py:469] NOT FOUND: PREVIOUS_SESSION_PATH
Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\_iblrig_tasks_trainingChoiceWorld.py", line 21, in <module>
    sph = SessionParamHandler(task_settings, user_settings)
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\session_params.py", line 75, in __init__
    self.REWARD_VALVE_TIME = adaptive.init_reward_valve_time(self)
  File "C:\iblrig_params\adaptive.py", line 94, in init_reward_valve_time
    if out >= sph.CALIB_FUNC_RANGE[1]:
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\pandas\core\generic.py", line 1576, in __nonzero__
    .format(self.__class__.__name__))
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Connected to https://alyx.internationalbrainlab.org as Karolina_Socha
2019-02-21 13:48:56.88 INFO     [registration.py:46] creating session for C:\iblrig_data\Subjects\_iblrig_calibration\2019-02-20\001
2019-02-21 13:48:56.137 ERROR    [registration.py:50] Subject: _iblrig_calibration doesn't exist in Alyx
2019-02-21 13:48:56.138 INFO     [registration.py:46] creating session for C:\iblrig_data\Subjects\_iblrig_calibration\2019-02-20\002
2019-02-21 13:48:56.189 ERROR    [registration.py:50] Subject: _iblrig_calibration doesn't exist in Alyx
done

```

**Comment by karolinasocha** [comment]
In 3rd rig I did the same steps (first I run calibration protocol, so the file is there). When I try run training ChoiceWorld the window with log to Alyx pops up but then it gave me same error that calibration does not exist in Alyx.

**Comment by GaelleChapuis** [comment]
Further: When logged in as Gaelle as user in pybpod, the error mentioned being login as Karolina:
![image](https://user-images.githubusercontent.com/43007596/53183971-2b85eb80-35f4-11e9-8c88-8835e5c363eb.png)


```
(base) C:\iblrig>pybpod
Finding pybpod folder...
Activating IBL environment...
Launching pybpod...
libpng warning: iCCP: known incorrect sRGB profile
21/02/2019 04:10:12 | WARNING | 5036 | pyforms_generic_editor.plugins.loader | install_plugins | Plugins path was not defined by user
libpng warning: iCCP: known incorrect sRGB profile
Different project data hashes:
2be610092d3b119c500dfdf7fbf79ac2b5eedefb2c9d2e1801a065d4a7aa87b1
c4bc59db1a286d0117ce7f98952cd550c10c45f7cb7c0f116af58d11440d27b8
Run protocol cannot be executed because project is not saved.
2019-02-21 16:11:26.960 INFO     [path_helper.py:469] NOT FOUND: PREVIOUS_DATA_FILE
2019-02-21 16:11:26.961 WARNING  [path_helper.py:488]
        ##########################################
            NOT FOUND: PREVIOUS_DATA_FILE
        ##########################################
                    USING INIT VALUES
        ##########################################
2019-02-21 16:11:26.961 INFO     [path_helper.py:469] NOT FOUND: PREVIOUS_SETTINGS_FILE
2019-02-21 16:11:26.962 INFO     [path_helper.py:469] NOT FOUND: PREVIOUS_SESSION_PATH
Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_habituationChoiceWorld\_iblrig_tasks_habituationChoiceWorld.py", line 19, in <module>
    sph = SessionParamHandler(task_settings, user_settings)
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_habituationChoiceWorld\session_params.py", line 67, in __init__
    self.REWARD_VALVE_TIME = adaptive.init_reward_valve_time(self)
  File "C:\iblrig_params\adaptive.py", line 94, in init_reward_valve_time
    if out >= sph.CALIB_FUNC_RANGE[1]:
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\pandas\core\generic.py", line 1576, in __nonzero__
    .format(self.__class__.__name__))
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Connected to https://alyx.internationalbrainlab.org as Karolina_Socha
done

```

**Comment by GaelleChapuis** [comment]
The same error occurs even when changing the ONE parameter file to my credentials and running pybpod locally:

![image](https://user-images.githubusercontent.com/43007596/53184876-c0d5af80-35f5-11e9-9433-4607cef5268d.png)

**Comment by GaelleChapuis** [comment]
When changing the task parameter to:
`AUTOMATIC_CALIBRATION = False `

this error occurs instead:
```

2019-02-21 16:32:39.994 INFO     [path_helper.py:469] NOT FOUND: PREVIOUS_DATA_FILE
2019-02-21 16:32:39.994 WARNING  [path_helper.py:488]
        ##########################################
            NOT FOUND: PREVIOUS_DATA_FILE
        ##########################################
                    USING INIT VALUES
        ##########################################
2019-02-21 16:32:39.995 INFO     [path_helper.py:469] NOT FOUND: PREVIOUS_SETTINGS_FILE
2019-02-21 16:32:39.996 INFO     [path_helper.py:469] NOT FOUND: PREVIOUS_SESSION_PATH
Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_habituationChoiceWorld\_iblrig_tasks_habituationChoiceWorld.py", line 19, in <module>
    sph = SessionParamHandler(task_settings, user_settings)
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_habituationChoiceWorld\session_params.py", line 102, in __init__
    iotasks.save_session_settings(self)
  File "C:\iblrig_params\iotasks.py", line 49, in save_session_settings
    f.write(json.dumps(sph_obj, cls=ComplexEncoder, indent=1))
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\encoder.py", line 439, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\iblrig_params\iotasks.py", line 24, in default
    return json.JSONEncoder.default(self, obj)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Series is not JSON serializable
Connected to https://alyx.internationalbrainlab.org as Gaelle
done
```

**Comment by nbonacchi** [comment]
this looks like a bug in the parsing of the previous calibration range file...
can you copy the contents of it here or better yet send me the latest calibration session for the rig that is having this mistake?

**Comment by GaelleChapuis** [comment]
I zipped the folder C:\iblrig_data\Subjects\_iblrig_calibration\2019-02-21 and sent to you over Slack.

**Comment by GaelleChapuis** [comment]
There were 3 folder in 2019-02-21 - we deleted 001 and 002, and renamed 003 to 001. Seeing the same error after this manip.
