### ISSUE TITLE
can't run tasks

### ISSUE THREAD

**Issue by ibldan** [int-brain-lab/iblrig#145]
> I can't run tasks in one of the rigs after updated. The error is like this:
`Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\_iblrig_tasks_trainingChoiceWorld.py", line 21, in <module>
    sph = SessionParamHandler(task_settings, user_settings)
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\session_params.py", line 99, in __init__
    output=self.SOFT_SOUND, samplerate=self.SOUND_SAMPLE_FREQ)
  File "C:\iblrig_params\sound.py", line 36, in configure_sounddevice
    devices) if 'XONAR SOUND CARD(64)' in d['name']][0][0]
IndexError: list index out of range
2019-02-28 18:19:03.64 ERROR    [webclient.py:194] <Response [400]>
Traceback (most recent call last):
  File "..\..\..\create_session.py", line 33, in <module>
    main()
  File "..\..\..\create_session.py", line 21, in main
    create(IBLRIG_DATA, dry=False)
  File "c:\ibllib\python\alf\one_iblrig.py", line 38, in create
    one = ONE()
  File "c:\ibllib\python\oneibl\one.py", line 101, in __init__
    base_url=self._par.ALYX_URL)
  File "c:\ibllib\python\oneibl\webclient.py", line 153, in __init__
    self.authenticate(**kwargs)
  File "c:\ibllib\python\oneibl\webclient.py", line 195, in authenticate
    raise Exception('Alyx authentication error. Check your credentials')
Exception: Alyx authentication error. Check your credentials`

I have tested the sound card . When I played the video, I can hear the sound. And the rigs come from Josh, it should be pre-installed.

**Comment by ibldan** [comment]
This issue is for rig3
