### ISSUE TITLE
can't update the rig

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#146]
When I run the update in one of the rigs, the error is like this:
`(base) C:\Users\IBLuser>cd C:\iblrig

(base) C:\iblrig>activate iblenv

(iblenv) C:\iblrig>python update.py
Traceback (most recent call last):
  File "update.py", line 152, in <module>
    info()
  File "update.py", line 131, in info
    update_remotes()
  File "update.py", line 109, in update_remotes
    subprocess.call(['git', 'remote', 'update'])
  File "C:\Users\IBLuser\Anaconda3\envs\iblenv\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\IBLuser\Anaconda3\envs\iblenv\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\IBLuser\Anaconda3\envs\iblenv\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified`

**Comment by GaelleChapuis** [comment]
For this rig, when try to run the task, the error is like this:
`Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\_iblrig_tasks_trainingChoiceWorld.py", line 21, in <module>
    sph = SessionParamHandler(task_settings, user_settings)
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\session_params.py", line 49, in __init__
    board=self.PYBPOD_BOARD, make=make)
  File "C:\iblrig_params\path_helper.py", line 29, in __init__
    self.IBLRIG_COMMIT_HASH = self._get_iblrig_commit_hash()
  File "C:\iblrig_params\path_helper.py", line 189, in _get_iblrig_commit_hash
    out = subprocess.check_output(["git", "rev-parse", "HEAD"]).decode()
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified`

**Comment by ibldan** [comment]
this is my rig (Berkeley-Dan), I just sign out Gaelle's account.  But the issue it there.

**Comment by ibldan** [comment]
this issue is for rig 1

**Comment by nbonacchi** [comment]
Looks like git is not installed...
Try installing git in iblenv.

**Comment by GaelleChapuis** [comment]
Why would Git not be installed? This rig comes straight from Sanworks.
Any way to check whether Git exists on iblenv before trying to install it @nbonacchi ?

**Comment by ibldan** [comment]
after installed， it works now. Gaelle ：you may close this issue, thanks.
