### ISSUE TITLE
errors after habituationChoiceWorld

### ISSUE THREAD

**Issue by ibldan** [int-brain-lab/iblrig#147]
After running habituationChoiceWorld, it connects to alyx as a user and shows up 2 errors (one is "IndexError", another related to "Unload") as below. I believe ONE is already setup and git is installed. May I have advice, please?

-----------------------------------------------------------------------
Connected to https://alyx.internationalbrainlab.org as feihu
2019-03-02 13:42:39.815 INFO     [registration.py:46] creating session for C:\iblrig_data\Subjects\DY_001\2019-02-28\001
Traceback (most recent call last):
  File "..\..\..\create_session.py", line 33, in <module>
    main()
  File "..\..\..\create_session.py", line 21, in main
    create(IBLRIG_DATA, dry=False)
  File "c:\ibllib\python\alf\one_iblrig.py", line 40, in create
    rc.create_sessions(root_data_folder, dry=dry)
  File "c:\ibllib\python\oneibl\registration.py", line 48, in create_sessions
    status_str = self.register_session(flag_file.parent, file_list=False)
  File "c:\ibllib\python\oneibl\registration.py", line 24, in func_wrapper
    f = func(self, sessionpath, *args, **kwargs)
  File "c:\ibllib\python\oneibl\registration.py", line 100, in register_session
    repository_name = [r for r in project['repositories'] if 'flatiron' not in r.lower()][0]
IndexError: list index out of range

Unhandled Exception: System.CannotUnloadAppDomainException: Error while unloading appdomain. (Exception from HRESULT: 0x80131015)
   at System.AppDomain.Unload(AppDomain domain)
   at Bonsai.Program.Main(String[] args)
   at Bonsai64.Program.Main(String[] args)

**Comment by nbonacchi** [comment]
This error you can ignore...

Unhandled Exception: System.CannotUnloadAppDomainException: Error while unloading appdomain. (Exception from HRESULT: 0x80131015)
at System.AppDomain.Unload(AppDomain domain)
at Bonsai.Program.Main(String[] args)
at Bonsai64.Program.Main(String[] args)

**Comment by nbonacchi** [comment]
The other is with the registration process, @oliche ?
