### ISSUE TITLE
could not open port COM for bpod

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#150]
After updating to latest version 3.7.5 I have error corresponding to COM port for bypbod.
COM4 was a port for bpod but now it is different (COM8). In Bonsai - pybpod boards- I change to COM8 for bpod but is seems that it did not update this information. I have the same error in other rigs.
```

2019-03-06 15:25:57.809 INFO     [_iblrig_tasks_habituationChoiceWorld.py:69] Starting trial: 3
Traceback (most recent call last):
 File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_habituationChoiceWorld\_iblrig_tasks_habituationChoiceWorld.py", line 109, in <module>
   bpod.run_state_machine(sma)  # Locks until state machine 'exit' is reached
 File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\pybpodapi\bpod\bpod_base.py", line 374, in run_state_machine
   self.session.add_trial_events()
 File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\pybpodapi\session.py", line 182, in add_trial_events
   (current_trial.state_timestamps[i], current_trial.state_timestamps[i + 1])]
IndexError: list index out of range
Traceback (most recent call last):
 File "..\..\..\bpod_lights.py", line 38, in <module>
   main(comport, int(command))
 File "..\..\..\bpod_lights.py", line 23, in main
   ser = serial.Serial(port=comport, baudrate=115200, timeout=1)
 File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\serial\serialwin32.py", line 31, in __init__
   super(Serial, self).__init__(*args, **kwargs)
 File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\serial\serialutil.py", line 240, in __init__
   self.open()
 File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\serial\serialwin32.py", line 62, in open
   raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM4': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
```

**Comment by karolinasocha** [comment]
I found it. It is in C:\iblrig_params\bpod_comports\

could not open port COM for bpod

**Comment by nbonacchi** [comment]
yes!
C:\iblrig_params\.bpod_comports.json
