### ISSUE TITLE
no error message in window prompt if there are no pulses from BNC1 (screen)

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#154]
This is example of detected pulses after behaviour training ( first 5 trials are correct and then next 5 trials are error trials)
![image](https://user-images.githubusercontent.com/32096962/54033547-80a52e00-41ac-11e9-82a8-02f6cf2dc720.png)

but in prompt window you do not have any error message about lack of signals from BNC1:

```
2019-03-08 11:48:44.158 INFO     [path_helper.py:473] NOT FOUND: LATEST_WATER_CALIBRATION_FILE
2019-03-08 11:48:44.158 WARNING  [path_helper.py:498]
        ##########################################
         NOT FOUND: LATEST_WATER_CALIBRATION_FILE
        ##########################################
2019-03-08 11:48:44.159 INFO     [path_helper.py:473] NOT FOUND: LATEST_WATER_CALIB_RANGE_FILE
2019-03-08 11:48:44.160 WARNING  [path_helper.py:507]
        ##########################################
         NOT FOUND: LATEST_WATER_CALIB_RANGE_FILE
        ##########################################
                  Using ms range(0, 1000)
        ##########################################

2019-03-08 11:48:44.160 INFO     [path_helper.py:473] NOT FOUND: PREVIOUS_DATA_FILE
2019-03-08 11:48:44.160 WARNING  [path_helper.py:492]
        ##########################################
            NOT FOUND: PREVIOUS_DATA_FILE
        ##########################################
                    USING INIT VALUES
        ##########################################
2019-03-08 11:48:44.161 INFO     [path_helper.py:473] NOT FOUND: PREVIOUS_SETTINGS_FILE
2019-03-08 11:48:44.162 INFO     [path_helper.py:473] NOT FOUND: PREVIOUS_SESSION_PATH
2019-03-08 11:48:53.943 INFO     [session_params.py:216]
##########################################
ADAPTIVE VALUES FOR CURRENT SESSION

REWARD AMOUNT:      3 µl
VALVE OPEN TIME:    0.067 sec
GAIN:               8.0 azimuth_degree/mm
IMPULSIVE CONTROL   OFF
##########################################
2019-03-08 11:48:57.747 INFO     [_iblrig_tasks_trainingChoiceWorld.py:89] Starting trial: 1
C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\online_plots.py:69: RuntimeWarning: invalid value encountered in true_divide
  prop_resp_ccw = ntrials_ccw / ntrials
c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\numpy\core\fromnumeric.py:2920: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\numpy\core\_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
2019-03-08 11:49:02.61 INFO     [trial_params.py:377]
##########################################
TRIAL NUM:            1
STIM POSITION:        -35
STIM CONTRAST:        0.5
STIM PHASE:           0.0
STIM PROB LEFT:       0.5
RESPONSE TIME:        2.5178000000000003

TRIAL CORRECT:        True

NTRIALS CORRECT:      1
NTRIALS ERROR:        0
WATER DELIVERED:      3
TIME FROM START:      0:00:22.838049
AMBIENT SENSOR DATA:  saved
##########################################
#############Next trial signed contrast: 0.5
2019-03-08 11:49:02.64 INFO     [_iblrig_tasks_trainingChoiceWorld.py:89] Starting trial: 2
2019-03-08 11:49:04.468 INFO     [trial_params.py:377]
##########################################
TRIAL NUM:            2
STIM POSITION:        35
STIM CONTRAST:        0.5
STIM PHASE:           0.0178371828288243
STIM PROB LEFT:       0.5
RESPONSE TIME:        0.798

TRIAL CORRECT:        True

NTRIALS CORRECT:      2
NTRIALS ERROR:        0
WATER DELIVERED:      6
TIME FROM START:      0:00:25.274131
AMBIENT SENSOR DATA:  saved
##########################################
#############Next trial signed contrast: -1.0
2019-03-08 11:49:04.472 INFO     [_iblrig_tasks_trainingChoiceWorld.py:89] Starting trial: 3
2019-03-08 11:49:06.820 INFO     [trial_params.py:377]
##########################################
TRIAL NUM:            3
STIM POSITION:        -35
STIM CONTRAST:        1.0
STIM PHASE:           3.132033611657525
STIM PROB LEFT:       0.5
RESPONSE TIME:        0.6503000000000001

TRIAL CORRECT:        True

NTRIALS CORRECT:      3
NTRIALS ERROR:        0
WATER DELIVERED:      9
TIME FROM START:      0:00:27.618861
AMBIENT SENSOR DATA:  saved
##########################################
#############Next trial signed contrast: -0.5
2019-03-08 11:49:06.824 INFO     [_iblrig_tasks_trainingChoiceWorld.py:89] Starting trial: 4
2019-03-08 11:49:09.409 INFO     [trial_params.py:377]
##########################################
TRIAL NUM:            4
STIM POSITION:        -35
STIM CONTRAST:        0.5
STIM PHASE:           0.5106595805604721
STIM PROB LEFT:       0.5
RESPONSE TIME:        0.8373000000000002

TRIAL CORRECT:        True

NTRIALS CORRECT:      4
NTRIALS ERROR:        0
WATER DELIVERED:      12
TIME FROM START:      0:00:30.193972
AMBIENT SENSOR DATA:  saved
##########################################
#############Next trial signed contrast: -1.0
2019-03-08 11:49:09.412 INFO     [_iblrig_tasks_trainingChoiceWorld.py:89] Starting trial: 5
2019-03-08 11:49:11.972 INFO     [trial_params.py:377]
##########################################
TRIAL NUM:            5
STIM POSITION:        -35
STIM CONTRAST:        1.0
STIM PHASE:           1.128910913315506
STIM PROB LEFT:       0.5
RESPONSE TIME:        0.7404000000000001

TRIAL CORRECT:        True

NTRIALS CORRECT:      5
NTRIALS ERROR:        0
WATER DELIVERED:      15
TIME FROM START:      0:00:32.769637
AMBIENT SENSOR DATA:  saved
##########################################
#############Next trial signed contrast: 0.5
2019-03-08 11:49:11.975 INFO     [_iblrig_tasks_trainingChoiceWorld.py:89] Starting trial: 6
2019-03-08 11:49:17.628 INFO     [trial_params.py:377]
##########################################
TRIAL NUM:            6
STIM POSITION:        35
STIM CONTRAST:        0.5
STIM PHASE:           1.255977921387908
STIM PROB LEFT:       0.5
RESPONSE TIME:        2.7833

TRIAL CORRECT:        False

NTRIALS CORRECT:      5
NTRIALS ERROR:        1
WATER DELIVERED:      15
TIME FROM START:      0:00:38.438040
AMBIENT SENSOR DATA:  saved
##########################################
#############Next trial signed contrast: -0.5
2019-03-08 11:49:17.631 INFO     [_iblrig_tasks_trainingChoiceWorld.py:89] Starting trial: 7
2019-03-08 11:49:20.802 INFO     [trial_params.py:377]
##########################################
TRIAL NUM:            7
STIM POSITION:        -35
STIM CONTRAST:        0.5
STIM PHASE:           0.46108453678424144
STIM PROB LEFT:       0.5
RESPONSE TIME:        0.5388999999999999

TRIAL CORRECT:        False

NTRIALS CORRECT:      5
NTRIALS ERROR:        2
WATER DELIVERED:      15
TIME FROM START:      0:00:41.601272
AMBIENT SENSOR DATA:  saved
##########################################
#############Next trial signed contrast: -0.5
2019-03-08 11:49:20.805 INFO     [_iblrig_tasks_trainingChoiceWorld.py:89] Starting trial: 8
2019-03-08 11:49:24.186 INFO     [trial_params.py:377]
##########################################
TRIAL NUM:            8
STIM POSITION:        -35
STIM CONTRAST:        0.5
STIM PHASE:           2.7053247664880606
STIM PROB LEFT:       0.5
RESPONSE TIME:        0.6784000000000001

TRIAL CORRECT:        False

NTRIALS CORRECT:      5
NTRIALS ERROR:        3
WATER DELIVERED:      15
TIME FROM START:      0:00:44.917528
AMBIENT SENSOR DATA:  saved
##########################################
#############Next trial signed contrast: 0.5
2019-03-08 11:49:24.190 INFO     [_iblrig_tasks_trainingChoiceWorld.py:89] Starting trial: 9
2019-03-08 11:49:27.538 INFO     [trial_params.py:377]
##########################################
TRIAL NUM:            9
STIM POSITION:        35
STIM CONTRAST:        0.5
STIM PHASE:           3.032319569294804
STIM PROB LEFT:       0.5
RESPONSE TIME:        0.6224000000000001

TRIAL CORRECT:        False

NTRIALS CORRECT:      5
NTRIALS ERROR:        4
WATER DELIVERED:      15
TIME FROM START:      0:00:48.338404
AMBIENT SENSOR DATA:  saved
##########################################
#############Next trial signed contrast: -0.5
2019-03-08 11:49:27.542 INFO     [_iblrig_tasks_trainingChoiceWorld.py:89] Starting trial: 10
2019-03-08 11:49:30.940 INFO     [trial_params.py:377]
##########################################
TRIAL NUM:            10
STIM POSITION:        -35
STIM CONTRAST:        0.5
STIM PHASE:           1.5956814725980073
STIM PROB LEFT:       0.4
RESPONSE TIME:        0.7496

TRIAL CORRECT:        False

NTRIALS CORRECT:      5
NTRIALS ERROR:        5
WATER DELIVERED:      15
TIME FROM START:      0:00:51.737848
AMBIENT SENSOR DATA:  saved
##########################################
#############Next trial signed contrast: -0.5
2019-03-08 11:49:30.943 INFO     [_iblrig_tasks_trainingChoiceWorld.py:89] Starting trial: 11
Connected to https://alyx.internationalbrainlab.org as Karolina_Socha
done

Unhandled Exception: System.CannotUnloadAppDomainException: Error while unloading appdomain. (Exception from HRESULT: 0x80131015)
   at System.AppDomain.Unload(AppDomain domain)
   at Bonsai.Program.Main(String[] args)
   at Bonsai64.Program.Main(String[] args)
```

**Comment by karolinasocha** [comment]
and this is result from running Nico's function: 
python post_session_check_sync_pulses.py 

![image](https://user-images.githubusercontent.com/32096962/54042832-fd430700-41c2-11e9-8bad-13a8d6b266ee.png)

to get this plot write in window prompt: 
```

(iblenv) C:\>cd C:\iblrig\tasks

(iblenv) C:\iblrig\tasks>python post_session_check_sync_pulses.py "C:\iblrig_data\Subjects\_iblrig_test_mouse\2019-03-08\001\raw_behavior_data\_iblrig_taskData.raw.jsonable"
```

**Comment by GaelleChapuis** [comment]
This relates to what we saw in Berkely (see https://github.com/int-brain-lab/iblrig/issues/77 ).
