### ISSUE TITLE
the process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#156]
When I stop habituation training this error occurs: the process cannot access the file because it is being used by another process. 

```
2019-03-12 11:12:19.512 INFO     [_iblrig_tasks_habituationChoiceWorld.py:69] Starting trial: 98
C:\iblrig_params\IBL\experiments\_iblrig_tasks\setups\habituationChoiceWorld\sessions\201903~1\20190312-105128.csv - The process cannot access the file because it is being used by another process.

Unhandled Exception: System.CannotUnloadAppDomainException: Error while unloading appdomain. (Exception from HRESULT: 0x80131015)
   at System.AppDomain.Unload(AppDomain domain)
   at Bonsai.Program.Main(String[] args)
   at Bonsai64.Program.Main(String[] args)
Connected to https://alyx.internationalbrainlab.org as Gaelle
2019-03-12 11:13:07.686 INFO     [registration.py:46] creating session for C:\iblrig_data\Subjects\KS008\2019-03-12\001
2019-03-12 11:13:07.739 ERROR    [registration.py:50] Subject: KS008 doesn't exist in Alyx
done

```

**Comment by nbonacchi** [comment]
you can ignore this error...
The order in which the post commands of the task are run is non deterministic so sometimes this will happen its just the cleanup method that cannot delete one unnecessary file because pybpod sometimes takes longer to release the lock on it, it should be deleted in the next session....
