### ISSUE TITLE
Sound issues

### ISSUE THREAD

**Issue by HernandoMV** [int-brain-lab/iblrig#157]
Error when running trainingChoiceWorld regarding sound.py not having a required attribute. Python rig is up to date. Reproduced in two different rigs

c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\numpy\core\fromnumeric.py:2920: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\numpy\core\_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\_iblrig_tasks_trainingChoiceWorld.py", line 21, in <module>
    sph = SessionParamHandler(task_settings, user_settings)
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\session_params.py", line 90, in __init__
    self.SOUND_SAMPLE_FREQ = sound.sound_sample_freq(self.SOFT_SOUND)
AttributeError: module 'sound' has no attribute 'sound_sample_freq'

**Comment by nbonacchi** [comment]
That's weird....
If you open C:\iblrig_params\sound.py does it have a sound_sample_freq function?
What about in C:\iblrig\tasks\sound.py?
If answer is no to the first and yes to the second try updating again...

**Comment by GaelleChapuis** [comment]
C:\iblrig_params\sound.py  has a function   sound_sample_freq .
C:\iblrig\tasks\sound.py  too.

Both look like :
```
def sound_sample_freq(soft_sound):
    if soft_sound == 'xonar':
        ssf = 192000
    elif soft_sound == 'sysdefault':
        ssf = 44100
    elif soft_sound is None:
        ssf = 96000
```

**Comment by GaelleChapuis** [comment]
It looks like the update did not go through properly. Re-did it, will let you know what happens.

**Comment by GaelleChapuis** [comment]
Ok, so the issue seems to be gone regarding the sound.
However, there is still an issue. There is no possibility to do water calibration on this rig at SWC as the scale is acting out. As a result we get an error (stating that a calibration file is missing) and cannot start any protocols. The calibration protocol has this output error:
```

Run protocol cannot be executed because project is not saved.
2019-03-12 15:27:31.702 INFO     [path_helper.py:473] NOT FOUND: VISUAL_STIMULUS_TYPE
2019-03-12 15:27:31.703 INFO     [path_helper.py:473] NOT FOUND: LATEST_WATER_CALIBRATION_FILE
2019-03-12 15:27:31.703 WARNING  [path_helper.py:498]
        ##########################################
         NOT FOUND: LATEST_WATER_CALIBRATION_FILE
        ##########################################
2019-03-12 15:27:31.703 INFO     [path_helper.py:473] NOT FOUND: LATEST_WATER_CALIB_RANGE_FILE
2019-03-12 15:27:31.704 WARNING  [path_helper.py:507]
        ##########################################
         NOT FOUND: LATEST_WATER_CALIB_RANGE_FILE
        ##########################################
                  Using ms range(0, 1000)
        ##########################################

2019-03-12 15:27:31.704 INFO     [path_helper.py:473] NOT FOUND: PREVIOUS_DATA_FILE
2019-03-12 15:27:31.705 WARNING  [path_helper.py:492]
        ##########################################
            NOT FOUND: PREVIOUS_DATA_FILE
        ##########################################
                    USING INIT VALUES
        ##########################################
2019-03-12 15:27:31.705 INFO     [path_helper.py:473] NOT FOUND: PREVIOUS_SETTINGS_FILE
2019-03-12 15:27:31.706 INFO     [path_helper.py:473] NOT FOUND: PREVIOUS_SESSION_PATH
Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_calibration_water\_iblrig_calibration_water.py", line 32, in <module>
    bpod = Bpod()
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\pybpodapi\bpod\bpod_io.py", line 28, in __init__
    super(BpodIO,self).__init__(serial_port, sync_channel, sync_mode)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\pybpodapi\bpod\bpod_com_protocol.py", line 44, in __init__
    if self.serial_port: self.open()
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\pybpodapi\bpod\bpod_com_protocol.py", line 48, in open
    super(BpodCOMProtocol, self).open()
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\pybpodapi\bpod\bpod_base.py", line 135, in open
    if not self._bpodcom_handshake():
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\pybpodapi\bpod\bpod_com_protocol.py", line 100, in _bpodcom_handshake
    response = self._arcom.read_char()  # Receive response
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\pybpodapi\com\arcom.py", line 148, in read_char
    return message_bytes.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xde in position 0: unexpected end of data


```

**Comment by GaelleChapuis** [comment]
Let's open a new issue about water calibration (scale), and close this one. 
@Hernando please open a new issue, I am closing this one.
