### ISSUE TITLE
no visual stimulation on the ipad screen

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#169]
**Describe the bug**
Visual stimulation is not displayed. There was no error message (see print screen below). I restarted several times pyBpod but still does not display visual styimulation.  
![image](https://user-images.githubusercontent.com/32096962/54677435-c7731c00-4afa-11e9-9408-a6dbdb8c68c7.png)

After stopping I have this error message but I am not sure if it is related to visual stimulation:
```

2019-03-20 10:25:33.3 INFO     [_iblrig_tasks_trainingChoiceWorld.py:89] Starting trial: 4
Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\_iblrig_tasks_trainingChoiceWorld.py", line 165, in <module>
    bpod.run_state_machine(sma)  # Locks until state machine 'exit' is reached
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\pybpodapi\bpod\bpod_base.py", line 365, in run_state_machine
    self.loop_handler()
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\_iblrig_tasks_trainingChoiceWorld.py", line 25, in bpod_loop_handler
    f.canvas.flush_events()  # 100µs
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\matplotlib\backends\_backend_tk.py", line 491, in flush_events
    self._master.update()
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\tkinter\__init__.py", line 1177, in update
    self.tk.call('update')
_tkinter.TclError: can't invoke "update" command: application has been destroyed
Connected to https://alyx.cortexlab.net as Karolina_Socha
done
```

**Comment by nbonacchi** [comment]
What's the error displayed in the cmd prompt?
The one that says Unhandled Exception:?

**Comment by karolinasocha** [comment]
```
2019-03-20 10:38:31.279 INFO     [path_helper.py:473] NOT FOUND: PREVIOUS_DATA_FILE
2019-03-20 10:38:31.279 WARNING  [path_helper.py:492]
        ##########################################
            NOT FOUND: PREVIOUS_DATA_FILE
        ##########################################
                    USING INIT VALUES
        ##########################################
2019-03-20 10:38:31.280 INFO     [path_helper.py:473] NOT FOUND: PREVIOUS_SETTINGS_FILE
2019-03-20 10:38:31.280 INFO     [path_helper.py:473] NOT FOUND: PREVIOUS_SESSION_PATH
OpenTK.Audio.AudioDeviceException: All attempts to open capture devices returned IntPtr.Zero. See debug log for verbose list.
   at OpenTK.Audio.AudioCapture..ctor(String deviceName, Int32 frequency, ALFormat sampleFormat, Int32 bufferSize)
   at Bonsai.Audio.AudioCapture.<>c__DisplayClass13.<.ctor>b__11()
   at System.Threading.Tasks.Task.Execute()
2019-03-20 10:38:39.571 INFO     [session_params.py:216]
##########################################
ADAPTIVE VALUES FOR CURRENT SESSION

REWARD AMOUNT:      3 µl
VALVE OPEN TIME:    0.067 sec
GAIN:               8.0 azimuth_degree/mm
IMPULSIVE CONTROL   OFF
##########################################
2019-03-20 10:38:43.384 INFO     [_iblrig_tasks_trainingChoiceWorld.py:89] Starting trial: 1

Unhandled Exception: System.CannotUnloadAppDomainException: Error while unloading appdomain. (Exception from HRESULT: 0x80131015)
   at System.AppDomain.Unload(AppDomain domain)
   at Bonsai.Program.Main(String[] args)
   at Bonsai64.Program.Main(String[] args)
```

**Comment by karolinasocha** [comment]
I ignored Unhandled Exception because it appeared before and I thought it is not related to visual stimulus. Now issue is that task runs but there is nothing on the display. I rebooted computer, plug and ub plug DP cable for ipad screen, check cables in Adafruit but nothing worked so far

**Comment by nbonacchi** [comment]
It looks like the microphone is not connected...
The stimulus workflow is the one that is also recording the audio (This should go into the video workflow in the future)
```
OpenTK.Audio.AudioDeviceException: All attempts to open capture devices returned IntPtr.Zero. See debug log for verbose list.
   at OpenTK.Audio.AudioCapture..ctor(String deviceName, Int32 frequency, ALFormat sampleFormat, Int32 bufferSize)
   at Bonsai.Audio.AudioCapture.<>c__DisplayClass13.<.ctor>b__11()
   at System.Threading.Tasks.Task.Execute()
```
this means Bonsai is not able to connect to the mic. Is the mic disconnected and the RECORD_SOUND flag set to True?

**Comment by karolinasocha** [comment]
True- thanks Nico. I thought that mic works independently to visual stimulus.
