### ISSUE TITLE
pybpod not opening correctly 

### ISSUE THREAD

**Issue by valagui** [int-brain-lab/iblrig#187]
Seems that pybpod paths were lost after re-starting the computer. Not sure if it is a bug or I did something wrong the following error occurs when trying to open pybpod from terminal
```Traceback (most recent call last):
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\pybpodgui_api\models\user\user_io.py", line 53, in load
    self.data = data = json.load(stream)
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\sca\formats\json.py", line 150, in load
    data = json.load(filestream)
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\pyforms_generic_editor\editor\base_editor.py", line 75, in init_form
    self.model.open_project(conf.DEFAULT_PROJECT_PATH)
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\pybpodgui_plugin\models\projects\projects_treenode.py", line 38, in open_project
    project = super().open_project(project_path)
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\pybpodgui_plugin\models\projects\projects_window.py", line 79, in open_project
    project.load(str(project_path))
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\pybpodgui_plugin\models\project\project_treenode.py", line 140, in load
    super(ProjectTreeNode, self).load(project_path)
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\pybpodgui_api\models\project\project_io.py", line 50, in load
    user.load( os.path.join(userspath, name))
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\pybpodgui_api\models\user\user_io.py", line 56, in load
    raise Exception('There was an error loading the configuration file for the subject [{0}]')
Exception: There was an error loading the configuration file for the subject [{0}]
Different project data hashes:
None
46a12a9670649582a4725e08390999d17ef8e7a7ffbb8075e52d1a37b114096e
done```

**Comment by anne-urai** [comment]
Solution (posting here for future reference): run `python update.py -v <current.version>`

**Comment by valagui** [comment]
How-To Solution: 
1) Restore items from Recycling Bin 
2) Open a shell and activate iblenv 
3) Run python update.py -v <current.version>
