### ISSUE TITLE
ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied; No module named 'iblrig'

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#212]
During updating python rigs to version 5.2.1 I had this error (in red)

```

ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'c:\\users\\ibluser\\anaconda3\\envs\\iblenv\\lib\\site-packages\\~-mpy\\.libs\\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll'
Consider using the `--user` option or check the permissions.

ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: C:\iblrig
Deleting untracked files
  Removed: C:\iblrig_params\user_settings.py
Copying general PyBpod IBL project settings
Traceback (most recent call last):
  File "update.py", line 297, in <module>
  File "update.py", line 234, in main
    os.system("conda deactivate && python install.py")
  File "update.py", line 207, in _update

  File "update.py", line 89, in import_tasks
    print("\nChecking out {}".format(ver))
  File "C:\iblrig\setup_default_config.py", line 426, in main
  File "C:\iblrig\setup_default_config.py", line 54, in copy_pybpod_user_settings
    (x / 'path_helper.py').unlink()
  File "C:\Users\IBLuser\Anaconda3\envs\iblenv\lib\shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\IBLuser\Anaconda3\envs\iblenv\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\iblrig\\scripts\\user_settings.py'
```

And after the update, when I tried to run pybod but I have just a blank screen:
![image](https://user-images.githubusercontent.com/32096962/61555974-895e1880-aa58-11e9-944c-02e2078fc2f0.png)

**Comment by karolinasocha** [comment]
You have to type twice python update.py -v 5.2.1
