### ISSUE TITLE
F2TTL caliration: HTTPError: <Response [404]

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#220]
**Describe the bug**
In my ephys rig I tried to run F2TTL calibration protocol but after turning the screen to black I got this error message and could not finish F2TTL calibration:

```
2019-07-26 15:00:00.233 INFO     [frame2TTL.py:130] Sending thresholds to device...
2019-07-26 15:00:00.234 INFO     [frame2TTL.py:90] Light threshold set to 37.0
2019-07-26 15:00:00.234 INFO     [frame2TTL.py:92] Dark threshold set to 77.0
2019-07-26 15:00:00.274 ERROR    [webclient.py:175] https://alyx.internationalbrainlab.org/locations/_iblrig_carandinilab_ephys_0
2019-07-26 15:00:00.276 ERROR    [webclient.py:176] {"detail":"Not found."}
2019-07-26 15:00:00.277 ERROR    [alyx.py:106] <Response [404]>
2019-07-26 15:00:00.316 ERROR    [webclient.py:175] https://alyx.internationalbrainlab.org/locations/_iblrig_carandinilab_ephys_0
2019-07-26 15:00:00.318 ERROR    [webclient.py:176] {"detail":"Not found."}
Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_calibration_frame2TTL\_iblrig_calibration_frame2TTL.py", line 30, in <module>
    alyx.update_board_params(sph.PYBPOD_BOARD, patch)
  File "c:\iblrig\iblrig\alyx.py", line 94, in update_board_params
    one.alyx.rest('locations', 'partial_update', id=board, data=patch_dict)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\webclient.py", line 372, in rest
    return self.patch('/' + endpoint + '/' + id.split('/')[-1], data=data)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\webclient.py", line 249, in patch
    return self._generic_request(requests.patch, rest_query, data=data)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\webclient.py", line 177, in _generic_request
    raise(requests.HTTPError(r))
requests.exceptions.HTTPError: <Response [404]>
```

**Comment by oliche** [comment]
Yes so you need to create the `_iblrig_carandinilab_ephys_0` board in the database.
Go to the admin interface, misc, lablocations and create a new one.

But shouldn't you be connecting to the cortexlab database instead ?

**Comment by karolinasocha** [comment]
Yes, it should be from alyx.cortexlab.net . I changed that only in this file C:\iblrig_params\user_settings.py

**Comment by karolinasocha** [comment]
Olivier, I have added _iblrig_carandinilab_ephys_0 to alyx of cortexlab.net and internationalbrainlab.org and now it worked. However I am not sure where I should change settings so it will login to https:/alyx.cortexlab.net.

**Comment by nbonacchi** [comment]
That's were the alyx problem came from!! 
If you add the same thing to both DB's it can screw up the ingestion... If you have an Alyx in your lab you should only be interacting with your cortxlab alyx for all things acquisition...
