### ISSUE TITLE
 Can't connect to https://alyx.internationalbrainlab.org

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#253]
Finding pybpod folder...
Launching pybpod...
libpng warning: iCCP: known incorrect sRGB profile
31/08/2019 02:02:38 | WARNING | 1764 | pyforms_generic_editor.plugins.loader | install_plugins | Plugins path was not defined by user
Traceback (most recent call last):
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\urllib3\connection.py", line 301, in connect
    conn = self._new_conn()
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0000026CD44677F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='alyx.internationalbrainlab.org', port=443): Max retries exceeded with url: /auth-token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000026CD44677F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\one.py", line 97, in __init__
    base_url=self._par.ALYX_URL)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\webclient.py", line 155, in __init__
    self.authenticate(**kwargs)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\webclient.py", line 193, in authenticate
    data=dict(username=username, password=password))
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='alyx.internationalbrainlab.org', port=443): Max retries exceeded with url: /auth-token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000026CD44677F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_ephysChoiceWorld\_iblrig_tasks_ephysChoiceWorld.py", line 14, in <module>
    from session_params import SessionParamHandler
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_ephysChoiceWorld\session_params.py", line 18, in <module>
    import iblrig.frame2TTL as frame2TTL
  File "c:\iblrig\iblrig\frame2TTL.py", line 7, in <module>
    import iblrig.alyx as alyx
  File "c:\iblrig\iblrig\alyx.py", line 19, in <module>
    one = ONE()
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\one.py", line 101, in __init__
    'Are you connecting from an IBL participating institution ?')
ConnectionError: Can't connect to https://alyx.internationalbrainlab.org.
IP addresses are filtered on IBL database servers.
Are you connecting from an IBL participating institution ?
Traceback (most recent call last):
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\urllib3\connection.py", line 301, in connect
    conn = self._new_conn()
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000002AF07239E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='alyx.internationalbrainlab.org', port=443): Max retries exceeded with url: /auth-token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002AF07239E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\one.py", line 97, in __init__
    base_url=self._par.ALYX_URL)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\webclient.py", line 155, in __init__
    self.authenticate(**kwargs)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\webclient.py", line 193, in authenticate    data=dict(username=username, password=password))
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='alyx.internationalbrainlab.org', port=443): Max retries exceeded with url: /auth-token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002AF07239E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:
```

Traceback (most recent call last):
  File "C:\iblrig\scripts\create_session.py", line 34, in <module>
    main()
  File "C:\iblrig\scripts\create_session.py", line 22, in main
    create(IBLRIG_DATA, dry=False)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\ibllib\pipes\experimental_data.py", line 48, in create
    one = ONE()
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\one.py", line 101, in __init__
    'Are you connecting from an IBL participating institution ?')
ConnectionError: Can't connect to https://alyx.internationalbrainlab.org.
IP addresses are filtered on IBL database servers.
Are you connecting from an IBL participating institution ?

```

**Comment by karolinasocha** [comment]
I have mouse on the rig and two probes inside the brain. I am sorry but this thing cannot happen again!
