### ISSUE TITLE
can't run tasks in the Behavioral PC for ephys

### ISSUE THREAD

**Issue by ibldan** [int-brain-lab/iblrig#255]
When run "HabituationChoiceWorld" in the Behavioral PC for ephys, get this error:

**
Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_habituationChoiceWorld\_iblrig_tasks_habituationChoiceWorld.py", line 12, in <module>
    from session_params import SessionParamHandler
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_habituationChoiceWorld\session_params.py", line 16, in <module>
    import iblrig.frame2TTL as frame2TTL
  File "c:\iblrig\iblrig\frame2TTL.py", line 7, in <module>
    import iblrig.alyx as alyx
  File "c:\iblrig\iblrig\alyx.py", line 19, in <module>
    one = ONE()
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\one.py", line 89, in __init__
    self._par = oneibl.params.get(silent=silent)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\params.py", line 101, in get
    par = iopar.read(_PAR_ID_STR)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\ibllib\io\params.py", line 62, in read
    par_dict = json.loads(fil.read())
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 19 (char 20)
Traceback (most recent call last):
  File "..\..\..\create_session.py", line 32, in <module>
    main()
  File "..\..\..\create_session.py", line 20, in main
    create(IBLRIG_DATA, dry=False)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\ibllib\pipes\experimental_data.py", line 48, in create
    one = ONE()
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\one.py", line 89, in __init__
    self._par = oneibl.params.get(silent=silent)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\oneibl\params.py", line 101, in get
    par = iopar.read(_PAR_ID_STR)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\ibllib\io\params.py", line 62, in read
    par_dict = json.loads(fil.read())
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 19 (char 20)
**

**Comment by nbonacchi** [comment]
Hey @ibldan 
Have you manged to fix this?
It looks like the .one_params file is not well formatted, this might happen if one forgets a quote or a comma somewhere. can you please check the file and let me know?

**Comment by ibldan** [comment]
Hi @nbonacchi 
I try, but it not working. Below is my .one_params file (in the folder C:\Users\IBLuser\AppData\Roaming):
{
    "ALYX_LOGIN": feihu,
    "ALYX_PWD": danlab123,
    "ALYX_URL": "https://alyx.internationalbrainlab.org",
    "CACHE_DIR": "C:\\Users\\IBLuser\\Downloads\\FlatIron",
    "FTP_DATA_SERVER": "ftp://ibl.flatironinstitute.org",
    "FTP_DATA_SERVER_LOGIN": "iblftp",
    "FTP_DATA_SERVER_PWD": "GrayMatter19",
    "HTTP_DATA_SERVER": "http://ibl.flatironinstitute.org",
    "HTTP_DATA_SERVER_LOGIN": "iblmember",
    "HTTP_DATA_SERVER_PWD": "GrayMatter19",
    "GLOBUS_CLIENT_ID": []
}
