### ISSUE TITLE
 v6.0.0 frame2TTL

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#262]
Ephys rig updated to v6.0.0 unfortunetly I could not run frame2TTL calibration and got this error:

```
2019-09-30 19:03:08.243 WARNING  [params.py:111] Params file does not exist, found old bpod_comports file. Trying to migrate...
Connected to https://alyx.internationalbrainlab.org as Karolina_Socha
2019-09-30 19:03:08.753 ERROR    [alyx.py:100] the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_calibration_frame2TTL\_iblrig_calibration_frame2TTL.py", line 13, in <module>
    sph = SessionParamHandler(task_settings, user_settings)
  File "C:\iblrig_params\IBL\tasks\_iblrig_calibration_frame2TTL\session_params.py", line 37, in __init__
    make=True)
  File "c:\iblrig\iblrig\path_helper.py", line 325, in __init__
    self.PARAMS = params.load_params_file()
  File "c:\iblrig\iblrig\params.py", line 112, in load_params_file
    try_migrate_to_params()
  File "c:\iblrig\iblrig\params.py", line 232, in try_migrate_to_params
    'F2TTL_DARK_THRESH': f2ttl_params['F2TTL_DARK_THRESH'],
TypeError: 'NoneType' object is not subscriptable
```

**Comment by karolinasocha** [comment]
and because of this I could not test training and ephys protocols (example error after trying to run trainingCW):

```
2019-09-30 19:13:18.939 WARNING  [params.py:111] Params file does not exist, found old bpod_comports file. Trying to migrate...
Connected to https://alyx.cortexlab.net as Karolina_Socha
2019-09-30 19:13:19.519 ERROR    [alyx.py:100] the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\_iblrig_tasks_trainingChoiceWorld.py", line 21, in <module>
    sph = SessionParamHandler(task_settings, user_settings)
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\session_params.py", line 46, in __init__
    make=make)
  File "c:\iblrig\iblrig\path_helper.py", line 325, in __init__
    self.PARAMS = params.load_params_file()
  File "c:\iblrig\iblrig\params.py", line 112, in load_params_file
    try_migrate_to_params()
  File "c:\iblrig\iblrig\params.py", line 232, in try_migrate_to_params
    'F2TTL_DARK_THRESH': f2ttl_params['F2TTL_DARK_THRESH'],
TypeError: 'NoneType' object is not subscriptable
```
