### ISSUE TITLE
pybpod stops working when start any task protocol in ephys rig;  v6.0.2 

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#265]
After update pybpod to version 6.0.2 Bpod (state machine) stops working when I start any protocol on my ephys rig (trainingCW, ephysCW, biasedCW); the stimulus is displayed normaly and does not stop session. Bpod turns off when I run training protocol and turns ON when I stop the session. I restarted bpod by unplugging USB cable from the computer.

I updated pybpod GUI to 6.0.2 in my training rigs and did not have this kind of issue. 

**Screenshots**
When I stop the task I have only this in cmd window: 
```
NTRIALS CORRECT:      0
NTRIALS ERROR:        2
WATER DELIVERED:      0 µl
TIME FROM START:      0:02:23.318794
TEMPERATURE:          25.479999542236328 ºC
AIR PRESSURE:         1028.74951171875 mb
RELATIVE HUMIDITY:    34.5966796875 %
##########################################
2019-10-02 10:54:53.721 INFO     [_iblrig_tasks_trainingChoiceWorld.py:100] Starting trial: 3
C:\iblrig_params\IBL\experiments\_iblrig_tasks\setups\trainingChoiceWorld\sessions\201910~1\20191002-105230.csv - The process cannot access the file because it is being used by another process.
System.InvalidOperationException: Sequence contains no elements.
Connected to https://alyx.cortexlab.net as Karolina_Socha
```

**Comment by nbonacchi** [comment]
The behaviorpc should be exactly the same as the training rigs PC, this is weird

**Comment by karolinasocha** [comment]
Nicco, just to clarify it was not pybpod (GUI) but bpod (state machine) that turned OFF. 
I downgraded to version 6.0.0 and had the same issue (stimulus was ON and trials seems to start but bpod was off again); I think it is something related to the state machine. 
When I tried to run the task and then stop, I had this error message:

```
2019-10-02 12:25:03.250 INFO     [_iblrig_tasks_trainingChoiceWorld.py:100] Starting trial: 1
2019-10-02 12:25:03.250 INFO     [_iblrig_tasks_trainingChoiceWorld.py:107] Waiting for camera pulses...
Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\_iblrig_tasks_trainingChoiceWorld.py", line 207, in <module>
    bpod.run_state_machine(sma)  # Locks until state machine 'exit' is reached
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\pybpodapi\bpod\bpod_base.py", line 322, in run_state_machine
    self.loop_handler()
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\_iblrig_tasks_trainingChoiceWorld.py", line 25, in bpod_loop_handler
    f.canvas.flush_events()  # 100µs
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\matplotlib\backends\_backend_tk.py", line 491, in flush_events
    self._master.update()
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\tkinter\__init__.py", line 1177, in update
    self.tk.call('update')
_tkinter.TclError: can't invoke "update" command: application has been destroyed
System.InvalidOperationException: Sequence contains no elements.
Connected to https://alyx.cortexlab.net as Karolina_Socha
done
```

**Comment by karolinasocha** [comment]
I solved this issue
