### ISSUE TITLE
No module named 'ibllib.pipes.misc'

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#292]
I did update of iblscripts on my ephys acquisition computer 
cd C:\iblscripts
git fetch
git pull

```
(base) C:\Users\IBL_ephys>cd C:\iblscripts

(base) C:\iblscripts>git fetch
warning: redirecting to https://github.com/int-brain-lab/iblscripts.git/
remote: Enumerating objects: 242, done.
remote: Counting objects: 100% (242/242), done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 530 (delta 200), reused 214 (delta 173), pack-reused 288
Receiving objects: 100% (530/530), 66.17 KiB | 915.00 KiB/s, done.
Resolving deltas: 100% (372/372), completed with 26 local objects.
From http://github.com/int-brain-lab/iblscripts
   559dbee..a501b33  master        -> origin/master
   c86cf5a..277b192  certification -> origin/certification
   c122f5a..0b8ce2d  develop       -> origin/develop
 * [new branch]      ephys_unmerge -> origin/ephys_unmerge

(base) C:\iblscripts>git pull
warning: redirecting to https://github.com/int-brain-lab/iblscripts.git/
Updating 559dbee..a501b33
Fast-forward
 deploy/ephyspc/create_custom_ephys_wiring.py       |  12 +
 deploy/ephyspc/ephyspc_params_file.py              |   6 +-
 deploy/ephyspc/misc.py                             | 264 ------------
 deploy/ephyspc/prepare_ephys_session.py            |   6 +-
 deploy/ephyspc/transfer_ephys_session.py           |  10 +-
 deploy/ephyspc/wirings/3A.wiring.json              |  18 +
 deploy/ephyspc/wirings/3B.wiring.json              |   7 +
 deploy/ephyspc/wirings/nidq.wiring.json            |  16 +
 deploy/serverpc/crontab/00_ALL.sh                  |  10 +-
 deploy/serverpc/crontab/01_extract.sh              |   3 -
 deploy/serverpc/crontab/01_extract_training.sh     |   5 +
 deploy/serverpc/crontab/02_register.sh             |   4 +-
 deploy/serverpc/crontab/03_compress.sh             |   3 -
 deploy/serverpc/crontab/03_compress_videos.sh      |   5 +
 deploy/serverpc/crontab/04_audio_training.sh       |   5 +
 .../05_dlc_training.sh}                            |   1 +
 deploy/serverpc/crontab/20_extract_ephys.sh        |   5 +
 deploy/serverpc/crontab/21_raw_ephys_qc.sh         |   4 +
 deploy/serverpc/crontab/22_audio_ephys.sh          |   5 +
 deploy/serverpc/crontab/23_compress_ephys.sh       |   5 +
 deploy/serverpc/crontab/25_spike_sorting_qc.sh     |   5 +
 deploy/serverpc/crontab/26_sync_merge_ephys.sh     |   5 +
 .../serverpc/crontab/27_compress_ephys_videos.sh   |   5 +
 deploy/serverpc/crontab/ephys.py                   |  75 ++++
 .../crontab/{experimental_data.py => training.py}  |   9 +-
 deploy/serverpc/crontab/update_ibllib.sh           |   4 +-
 deploy/serverpc/ephys/01_extract_ephys.sh          |   4 -
 deploy/serverpc/ephys/02_qc_ephys.sh               |   4 -
 deploy/serverpc/ephys/ephys.py                     |  50 ---
 deploy/serverpc/kilosort2/run_ks2_ibl.m            |   8 +-
 deploy/serverpc/utils/batch_ks2.m                  |  18 +
 deploy/serverpc/utils/rerun.py                     | 207 ++++++++--
 deploy/serverpc/utils/wiring_files_copy.py         |  39 ++
 .../workflows/three_cameras_record_biasedCW.bonsai | 241 +++++++++++
 .../three_cameras_record_biasedCW.bonsai.layout    | 459 +++++++++++++++++++++
 deploy/videopc/misc.py                             | 264 ------------
 deploy/videopc/prepare_video_session.py            |  15 +-
 deploy/videopc/transfer_video_session.py           |  44 +-
 deploy/videopc/videopc_params_file.py              |   6 +-
 tests/test_audio_extraction.py                     |  18 +-
 tests/test_ephys_compression_pipeline.py           |  48 +++
 tests/test_ephys_extraction_choiceWorld.py         |   8 +-
 tests/test_transfer_rig_data.py                    |  82 ++--
 ...video_training.py => test_video_compression.py} |  31 +-
 44 files changed, 1329 insertions(+), 714 deletions(-)
 create mode 100644 deploy/ephyspc/create_custom_ephys_wiring.py
 delete mode 100644 deploy/ephyspc/misc.py
 create mode 100644 deploy/ephyspc/wirings/3A.wiring.json
 create mode 100644 deploy/ephyspc/wirings/3B.wiring.json
 create mode 100644 deploy/ephyspc/wirings/nidq.wiring.json
 delete mode 100755 deploy/serverpc/crontab/01_extract.sh
 create mode 100755 deploy/serverpc/crontab/01_extract_training.sh
 delete mode 100755 deploy/serverpc/crontab/03_compress.sh
 create mode 100755 deploy/serverpc/crontab/03_compress_videos.sh
 create mode 100755 deploy/serverpc/crontab/04_audio_training.sh
 rename deploy/serverpc/{dlc/video_pipelines.sh => crontab/05_dlc_training.sh} (93%)
 create mode 100755 deploy/serverpc/crontab/20_extract_ephys.sh
 create mode 100755 deploy/serverpc/crontab/21_raw_ephys_qc.sh
 create mode 100755 deploy/serverpc/crontab/22_audio_ephys.sh
 create mode 100755 deploy/serverpc/crontab/23_compress_ephys.sh
 create mode 100755 deploy/serverpc/crontab/25_spike_sorting_qc.sh
 create mode 100755 deploy/serverpc/crontab/26_sync_merge_ephys.sh
 create mode 100755 deploy/serverpc/crontab/27_compress_ephys_videos.sh
 create mode 100644 deploy/serverpc/crontab/ephys.py
 rename deploy/serverpc/crontab/{experimental_data.py => training.py} (81%)
 delete mode 100755 deploy/serverpc/ephys/01_extract_ephys.sh
 delete mode 100755 deploy/serverpc/ephys/02_qc_ephys.sh
 delete mode 100644 deploy/serverpc/ephys/ephys.py
 create mode 100644 deploy/serverpc/utils/batch_ks2.m
 create mode 100644 deploy/serverpc/utils/wiring_files_copy.py
 create mode 100644 deploy/videopc/bonsai/workflows/three_cameras_record_biasedCW.bonsai
 create mode 100644 deploy/videopc/bonsai/workflows/three_cameras_record_biasedCW.bonsai.layout
 delete mode 100644 deploy/videopc/misc.py
 create mode 100644 tests/test_ephys_compression_pipeline.py
 rename tests/{test_video_training.py => test_video_compression.py} (58%)
```

but now I cannot create a session folder:

```
(base) C:\iblscripts>
(base) C:\iblscripts>conda activate iblenv

(iblenv) C:\iblscripts>cd C:\iblscripts\deploy\ephyspc

(iblenv) C:\iblscripts\deploy\ephyspc>python .\prepare_ephys_session.py KS003
Traceback (most recent call last):
  File ".\prepare_ephys_session.py", line 10, in <module>
    from ibllib.pipes.misc import load_ephyspc_params
ModuleNotFoundError: No module named 'ibllib.pipes.misc'

(iblenv) C:\iblscripts\deploy\ephyspc>cd C:\iblscripts

(iblenv) C:\iblscripts>git fetch
warning: redirecting to https://github.com/int-brain-lab/iblscripts.git/

(iblenv) C:\iblscripts>git pull
warning: redirecting to https://github.com/int-brain-lab/iblscripts.git/
Already up to date.

(iblenv) C:\iblscripts>
(iblenv) C:\iblscripts>conda activate iblenv

(iblenv) C:\iblscripts>cd C:\iblscripts\deploy\ephyspc

(iblenv) C:\iblscripts\deploy\ephyspc>python .\prepare_ephys_session.py KS003
Traceback (most recent call last):
  File ".\prepare_ephys_session.py", line 10, in <module>
    from ibllib.pipes.misc import load_ephyspc_params
ModuleNotFoundError: No module named 'ibllib.pipes.misc'

(iblenv) C:\iblscripts\deploy\ephyspc>python .\prepare_ephys_session.py KS003
Traceback (most recent call last):
  File ".\prepare_ephys_session.py", line 10, in <module>
    from ibllib.pipes.misc import load_ephyspc_params
ModuleNotFoundError: No module named 'ibllib.pipes.misc'
```

**Comment by nbonacchi** [comment]
You need to update ibllib: 
like this:
https://docs.google.com/document/d/1jwqQJWfTEwZgLKsjBVf0TRSu6QiXVvspladlxDh-CIs/edit#heading=h.ouc07ahhf580
or here:
https://docs.google.com/document/d/1Nkla7Or2vbevHUZIqVgobEoY0ZNhKk-3JIW2FcOekuw/edit#heading=h.gyc81ajzjhpi
