### ISSUE TITLE
biasedCW in ephys rig; does not start the trial; no stimulus on the screen

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#293]
Suddenly, I cannot start the session with biasedCW in my ephys rig. "Suddenly" because I have just finished one training session and I was starting 2nd with different subject (so nothing on the rig changed).
Everything is ON but there is no stimulus showing on the screen and there is no sound cue to start the trial.  It does not give any error. I restarted computer; unplugged state machine and rotary encoder USBs, uploaded these devices in pybpod GUI. Everything is connected, no error occurred. Cameras are ON

```
Finding pybpod folder...
Launching pybpod...
libpng warning: iCCP: known incorrect sRGB profile
20/11/2019 12:13:45 | WARNING | 11472 | pyforms_generic_editor.plugins.loader | install_plugins | Plugins path was not defined by user
2019-11-20 12:14:02.665 INFO     [frame2TTL.py:91] Light threshold set to 46.0
2019-11-20 12:14:02.665 INFO     [frame2TTL.py:93] Dark threshold set to 86.0
2019-11-20 12:14:02.666 INFO     [frame2TTL.py:178] Frame2TTL: Thresholds set.
2019-11-20 12:14:12.722 INFO     [user_input.py:180] Subject weight 25.4
2019-11-20 12:14:15.316 INFO     [session_params.py:229]
##########################################
PREVIOUS SESSION FOUND
LOADING PARAMETERS FROM:       c:\iblrig_data\Subjects\KS014\2019-11-19\001\raw_behavior_data\_iblrig_taskData.raw.jsonable

PREVIOUS NTRIALS:              185
PREVIOUS WATER DRANK:          166.5
LAST REWARD:                   1.5
LAST GAIN:                     4.0
PREVIOUS WEIGHT:               26.7
##########################################
2019-11-20 12:14:20.616 INFO     [_iblrig_tasks_biasedChoiceWorld.py:105] Starting trial: 1
2019-11-20 12:14:20.620 INFO     [_iblrig_tasks_biasedChoiceWorld.py:112] First trial initializing, will move to next trial only if:
2019-11-20 12:14:20.621 INFO     [_iblrig_tasks_biasedChoiceWorld.py:113] 1. camera is detected
2019-11-20 12:14:20.623 INFO     [_iblrig_tasks_biasedChoiceWorld.py:114] 2. 0 sec have elapsed
2019-11-20 12:14:20.625 INFO     [_iblrig_tasks_biasedChoiceWorld.py:115] 3. visual stimulus is detected
```
Below gif from starting the session:
![biasedCW_freeze](https://user-images.githubusercontent.com/32096962/69238681-75eec580-0b90-11ea-9b32-c17699571455.gif)

**Comment by karolinasocha** [comment]
I updated pybpod (last time updating to the latest version helped debugging something similar) but now I cannot run pybpod GUI anymore:

```
C:\iblrig
 C:\iblrig_params
Fetching origin
Available branches: ['develop', 'feature/passive', 'master', 'sfn_humantask']
Available versions: ['5.3.1', '6.0.0', '6.0.1', '6.0.2', '6.0.3', '6.0.4', '6.0.5', '6.0.6', '6.1.0', '6.1.1', '6.1.2', '6.1.3']
Current branch: (HEAD detached at 6.1.3)
Current version: 6.1.3

Finding pybpod folder...
Launching pybpod...
EOL while scanning string literal (user_settings.py, line 52)
Traceback (most recent call last):
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\pybpodgui_plugin\__main__.py", line 28, in <module>
    import user_settings
  File "C:\iblrig_params\user_settings.py", line 52
    ALYX_PLUGIN_ADDRESS = 'https://alyx.cortexlab.net
                                                    ^
SyntaxError: EOL while scanning string literal
Traceback (most recent call last):
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\pybpodgui_plugin\__main__.py", line 28, in <module>
    import user_settings
  File "C:\iblrig_params\user_settings.py", line 52
    ALYX_PLUGIN_ADDRESS = 'https://alyx.cortexlab.net
                                                    ^
SyntaxError: EOL while scanning string literal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\IBLuser\Anaconda3\envs\iblenv\Scripts\start-pybpod.exe\__main__.py", line 5, in <module>
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\pybpodgui_plugin\__main__.py", line 67, in <module>
    settings.GENERIC_EDITOR_TITLE                   = 'PLEASE EDIT USER SETTINGS AND RESTART APP'
NameError: name 'settings' is not defined
done
```

**Comment by karolinasocha** [comment]
I found what I did wrong that I could not launch pybpod: I accidentally removed ' from that line:
 ALYX_PLUGIN_ADDRESS = 'https://alyx.cortexlab.net'

**Comment by karolinasocha** [comment]
Updating pybpod helped.

In cmd window:
conda activate iblenv
python update.py -v 6.1.3
