### ISSUE TITLE
cannot transfer ephys data to local server part2

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#295]
One data has been successfully transferred (2019-11-20) however I could not transfer data set from 2019-11-21:

```
Found session: D:\SGL_DATA\Subjects\KS003\2019-11-20\001
Transfer to Y:\Subjects with the same name?
[y]es/[r]ename/[s]kip/[e]xit
 ^
> y
y
Attempting to copy:
D:\SGL_DATA\Subjects\KS003\2019-11-20\001\raw_ephys_data
--> Y:\Subjects\KS003\2019-11-20\001\raw_ephys_data
Copying all files:
D:\SGL_DATA\Subjects\KS003\2019-11-20\001\raw_ephys_data
--> Y:\Subjects\KS003\2019-11-20\001\raw_ephys_data
All files copied

Found session: D:\SGL_DATA\Subjects\KS003\2019-11-21
Traceback (most recent call last):
  File "C:\Users\IBL_ephys\Miniconda3\envs\iblenv\lib\shutil.py", line 550, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\SGL_DATA\\Subjects\\KS003\\2019-11-21\\001\\raw_ephys_data\\probe00\\_spikeglx_ephysData_g0_t0.imec0.ap.bin' -> 'D:\\SGL_DATA\\Subjects\\KS003\\2019-11-21\\raw_ephys_data\\probe00\\_spikeglx_ephysData_g0_t0.imec0.ap.bin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "transfer_ephys_session.py", line 26, in <module>
    iblscripts_folder=iblscripts_folder)
  File "C:\Users\IBL_ephys\Miniconda3\envs\iblenv\lib\site-packages\ibllib\pipes\misc.py", line 232, in confirm_ephys_remote_folder
    move_ephys_files(str(session_path))
  File "C:\Users\IBL_ephys\Miniconda3\envs\iblenv\lib\site-packages\ibllib\pipes\misc.py", line 376, in move_ephys_files
    shutil.move(str(i0f), str(probe00_path / i0f.name))
  File "C:\Users\IBL_ephys\Miniconda3\envs\iblenv\lib\shutil.py", line 564, in move
    copy_function(src, real_dst)
  File "C:\Users\IBL_ephys\Miniconda3\envs\iblenv\lib\shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\IBL_ephys\Miniconda3\envs\iblenv\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\SGL_DATA\\Subjects\\KS003\\2019-11-21\\raw_ephys_data\\probe00\\_spikeglx_ephysData_g0_t0.imec0.ap.bin'

```

Folders raw_ephys_data\\probe00 and raw_ephys_data\\probe01 have not been created on server computer.
My action: I created these folders manually (on server computer) and re-do transfer however I had the same error message. 
The difference between 20-11 and 21-11 is that I copied before data from 20-11 to my local server manually.

**Comment by karolinasocha** [comment]
I created again `transfer_me.flag` file and this time I got this message:

```
(iblenv) C:\iblscripts\deploy\ephyspc>python transfer_ephys_session.py
LOCAL: D:\SGL_DATA\Subjects
REMOTE: Y:\Subjects
Nothing to transfer, exiting...
(iblenv) C:\iblscripts\deploy\ephyspc>

```

**Comment by karolinasocha** [comment]
After recordings I tired to transfer data but got this message:
it seems that it tries to find this folder :` FileNotFoundError: [Errno 2] No such file or directory: 'D:\\iblrig_data\\Subjects\\KS014\\2019-12-03\\raw_ephys_data\\probe00\\_spikeglx_ephysData_g0_t0.imec0.ap.bin'`

```
(iblenv) C:\iblscripts\deploy\ephyspc>python transfer_ephys_session.py
LOCAL: D:\iblrig_data\Subjects
REMOTE: Y:\Subjects

Found session: D:\iblrig_data\Subjects\KS014\2019-12-03
Traceback (most recent call last):
  File "C:\Users\IBL_ephys\Miniconda3\envs\iblenv\lib\shutil.py", line 550, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\iblrig_data\\Subjects\\KS014\\2019-12-03\\001\\raw_ephys_data\\probe00\\_spikeglx_ephysData_g0_t0.imec0.ap.bin' -> 'D:\\iblrig_data\\Subjects\\KS014\\2019-12-03\\raw_ephys_data\\probe00\\_spikeglx_ephysData_g0_t0.imec0.ap.bin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "transfer_ephys_session.py", line 26, in <module>
    iblscripts_folder=iblscripts_folder)
  File "C:\Users\IBL_ephys\Miniconda3\envs\iblenv\lib\site-packages\ibllib\pipes\misc.py", line 230, in confirm_ephys_remote_folder
    move_ephys_files(str(session_path))
  File "C:\Users\IBL_ephys\Miniconda3\envs\iblenv\lib\site-packages\ibllib\pipes\misc.py", line 379, in move_ephys_files
    shutil.move(str(i0f), str(probe00_path / i0f.name))
  File "C:\Users\IBL_ephys\Miniconda3\envs\iblenv\lib\shutil.py", line 564, in move
    copy_function(src, real_dst)
  File "C:\Users\IBL_ephys\Miniconda3\envs\iblenv\lib\shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\IBL_ephys\Miniconda3\envs\iblenv\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\iblrig_data\\Subjects\\KS014\\2019-12-03\\raw_ephys_data\\probe00\\_spikeglx_ephysData_g0_t0.imec0.ap.bin'

(iblenv) C:\iblscripts\deploy\ephyspc>
(iblenv) C:\iblscripts\deploy\ephyspc>
```
