### ISSUE TITLE
AssertionError: src_files != dst_files after copying data to local server

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#301]
I left computer to copy data but the next day I saw that I got this message:
I checked folder in local server and it seems that data is there. I am not sure if this is something that I should worry about?

```

Attempting to copy:
D:\iblrig_data\Subjects\KS014\2019-12-06\001\raw_ephys_data
--> Y:\Subjects\KS014\2019-12-06\001\raw_ephys_data
Copying all files:
D:\iblrig_data\Subjects\KS014\2019-12-06\001\raw_ephys_data
--> Y:\Subjects\KS014\2019-12-06\001\raw_ephys_data
Traceback (most recent call last):
  File "transfer_ephys_session.py", line 26, in <module>
    iblscripts_folder=iblscripts_folder)
  File "C:\Users\IBL_ephys\Miniconda3\envs\iblenv\lib\site-packages\ibllib\pipes\misc.py", line 259, in confirm_ephys_remote_folder
    force=force)
  File "C:\Users\IBL_ephys\Miniconda3\envs\iblenv\lib\site-packages\ibllib\pipes\misc.py", line 78, in transfer_folder
    if check_transfer(src, dst) is None:
  File "C:\Users\IBL_ephys\Miniconda3\envs\iblenv\lib\site-packages\ibllib\pipes\misc.py", line 41, in check_transfer
    assert len(src_files) == len(dst_files), assert_msg
AssertionError: src_files != dst_files

(iblenv) C:\iblscripts\deploy\ephyspc>
```

**Comment by karolinasocha** [comment]
After copying files I had that message:

```
Attempting to copy:
D:\iblrig_data\Subjects\KS016\2019-12-06\001\raw_ephys_data
--> Y:\Subjects\KS016\2019-12-06\001\raw_ephys_data
Copying all files:
D:\iblrig_data\Subjects\KS016\2019-12-06\001\raw_ephys_data
--> Y:\Subjects\KS016\2019-12-06\001\raw_ephys_data
All files copied
Traceback (most recent call last):
  File "transfer_ephys_session.py", line 26, in <module>
    iblscripts_folder=iblscripts_folder)
  File "C:\Users\IBL_ephys\Miniconda3\envs\iblenv\lib\site-packages\ibllib\pipes\misc.py", line 266, in confirm_ephys_remote_folder
    create_ephys_flags(remote_session_path)
  File "C:\Users\IBL_ephys\Miniconda3\envs\iblenv\lib\site-packages\ibllib\pipes\misc.py", line 276, in create_ephys_flags
    flags.write_flag_file(probe01_path.joinpath('spike_sorting.flag'))
  File "C:\Users\IBL_ephys\Miniconda3\envs\iblenv\lib\site-packages\ibllib\io\flags.py", line 96, in write_flag_file
    with open(fname, mode) as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'Y:\\Subjects\\KS016\\2019-12-06\\001\\raw_ephys_data\\probe01\\spike_sorting.flag'

(iblenv) C:\iblscripts\deploy\ephyspc>

```
