### ISSUE TITLE
empty .iblrig_params.json file

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#325]
**Describe the bug**
After restarting training after a two-month break, two of our rigs showed the following problem:

```
Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_biasedChoiceWorld\_iblrig_tasks_biasedChoiceWorld.py", line 22, in <module>
    sph = SessionParamHandler(task_settings, user_settings)
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_biasedChoiceWorld\session_params.py", line 54, in __init__
    self.PYBPOD_SUBJECTS[0], protocol=self.PYBPOD_PROTOCOL, make=make
  File "c:\iblrig\iblrig\path_helper.py", line 349, in __init__
    self._BOARD = params.get_board_name()
  File "c:\iblrig\iblrig\params.py", line 84, in get_board_name
    pars = load_params_file()
  File "c:\iblrig\iblrig\params.py", line 152, in load_params_file
    out = json.load(f)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\iblrig\scripts\bpod_lights.py", line 12, in <module>
    comport = params.get_board_comport()
  File "c:\iblrig\iblrig\params.py", line 103, in get_board_comport
    pars = load_params_file()
  File "c:\iblrig\iblrig\params.py", line 152, in load_params_file
    out = json.load(f)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Connected to https://alyx.internationalbrainlab.org as anneu
done
```

which was caused by an empty `.iblrig_params.json` file. In both cases, we had just re-run all calibrations; and on one rig, animals had already successfully done the task the day before. I have no idea how the `.iblrig_params.json` file can suddenly be empty.

Posting here, in case anyone has the same problem: this error can be solved be deleting/renaming the `.iblrig_params.json` file. Then start pybpod and launch a task with a test mouse; it will ask you to re-enter the COMports of the RE and frame2TTL. You'll then have to re-run the frame2TTL calibration, water calibration and bpod_ttl_test.

**Comment by anne-urai** [comment]
Tip: to avoid issues with an empty `.iblrig_params.json` file (for example when Windows decides to update on your rig), copy the file to your desktop (or somewhere else safe) after all your calibrations have been done. This means that if there is a crash, you can simply copy the file back into place, without having to rerun all calibrations (which can be time consuming).

**Comment by alejandropan** [comment]
@nbonacchi This happened a couple of times this week.  I believe if something related to the water calibration. In both instances it happened right after that.

**Comment by nbonacchi** [comment]
Thanks, that helps! I'll have a look.

**Comment by nbonacchi** [comment]
Added backup params file on develop: 9c5988c8d83df34412ebab7c2519e8c1a08d6d65
