### ISSUE TITLE
Bpod shuts down 

### ISSUE THREAD

**Issue by Petrina-Lau** [int-brain-lab/iblrig#357]
Bpod in the EPhys rig shut down after running flush water. 

Bpod was working well before but as I was trouble shooting for another issue, I disconnected Rotary encoder circuit board while bpod was running a protocol, bpod crashed (without shutting down). When I restart bpod, it shuts down whenever I run flush water but It can still do frame2ttl calibration.  same for other protocols. 

Same ValueError: I?O opeation on closed file. 

I've re-installed the iblenv and iblrig but issue persists.

*Below is the error, observed after running Flush water and bpod shut down: 

base) c:\iblrig>conda activate iblenv

(iblenv) c:\iblrig>pybpod
Activating IBL environment...
Finding iblrig folder...
Updating update routines...
c:\iblrig
 c:\iblrig_params
Fetching origin
Available branches: ['develop', 'feature/async_plots', 'feature/refactoring_alyx', 'master', 'migrate_ibllib_funcs', 'opto_task', 'rc', 'sfn_humantask']
Available versions: ['6.2.5', '6.4.0', '6.4.1', '6.4.2']
Current branch: master
Current version: 6.4.2
Checked out update.py from branch master

Checking for updates...
c:\iblrig
 c:\iblrig_params
Fetching origin
Available branches: ['develop', 'feature/async_plots', 'feature/refactoring_alyx', 'master', 'migrate_ibllib_funcs', 'opto_task', 'rc', 'sfn_humantask']
Available versions: ['6.2.5', '6.4.0', '6.4.1', '6.4.2']
Current branch: master
Current version: 6.4.2

Finding pybpod folder...
Launching pybpod...
libpng warning: iCCP: known incorrect sRGB profile
19/05/2021 01:36:20 | WARNING | 4040 | pyforms_generic_editor.plugins.loader | install_plugins | Plugins path was not defined by user
Starting trial:  1
main
Traceback (most recent call last):
  File "c:\anaconda3\envs\iblenv\lib\site-packages\pybpodgui_api\models\board\board_com.py", line 253, in run_task_handler
    self.end_run_task_handler()
  File "c:\anaconda3\envs\iblenv\lib\site-packages\pybpodgui_plugin\models\board\board_com.py", line 68, in end_run_task_handler
    super(BoardCom, self).end_run_task_handler()
  File "c:\anaconda3\envs\iblenv\lib\site-packages\pybpodgui_api\models\board\board_com.py", line 291, in end_run_task_handler
    session.load_contents()
  File "c:\anaconda3\envs\iblenv\lib\site-packages\pybpodgui_plugin\models\session\session_window.py", line 83, in load_contents
    super(SessionWindow, self).load_contents()
  File "c:\anaconda3\envs\iblenv\lib\site-packages\pybpodgui_api\models\session\session_io.py", line 114, in load_contents
    memory_map=True
  File "c:\anaconda3\envs\iblenv\lib\site-packages\pandas\io\parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "c:\anaconda3\envs\iblenv\lib\site-packages\pandas\io\parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "c:\anaconda3\envs\iblenv\lib\site-packages\pandas\io\parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "c:\anaconda3\envs\iblenv\lib\site-packages\pandas\io\parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "c:\anaconda3\envs\iblenv\lib\site-packages\pandas\io\parsers.py", line 1898, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas\_libs\parsers.pyx", line 518, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 620, in pandas._libs.parsers.TextReader._get_header
  File "pandas\_libs\parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas\_libs\parsers.pyx", line 1940, in pandas._libs.parsers.raise_parser_error
ValueError: I/O operation on closed file.
done

**Comment by nbonacchi** [comment]
Check/reset Bpod or switch it back to the one that was working? (We changed it while troublesooting the sound issues you had)

**Comment by Petrina-Lau** [comment]
But all bpod should work, right? just need to change the COM port at .parameter and at bpod GUI? And the Frame2TTL calibration worked, so PC should be able to communicate with the PC ?
