### ISSUE TITLE
Bonsai crash stacktrace

### ISSUE THREAD

**Issue by nbonacchi** [int-brain-lab/iblrig#371]
Bonsai freeze on start running training on ephys rig:
```
Unhandled Exception: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'EditorForm'.
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Form.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.GetSafeHandle(IWin32Window window)
   at System.Windows.Forms.MessageBox.ShowCore(IWin32Window owner, String text, String caption, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defaultButton, MessageBoxOptions options, Boolean showHelp)
   at Bonsai.Editor.EditorForm.<>c__DisplayClass137_0.<HandleWorkflowError>b__0()
   at Bonsai.Editor.EditorForm.HandleWorkflowError(Exception e)
   at Bonsai.Editor.EditorForm.HandleSchedulerError(Exception e)
   at System.Reactive.Concurrency.CatchScheduler`1.<>c__DisplayClass5`1.<Wrap>b__4(IScheduler self, TState state)
   at System.Reactive.Concurrency.EventLoopScheduler.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by micheleangelofabbri** [comment]
Outdated issue.
