### ISSUE TITLE
Inability to start task after reinstalling both versions 6.4.2 and 6.4.3 in the aftermath of having the code updated

### ISSUE THREAD

**Issue by srhaiken** [int-brain-lab/iblrig#372]
My behavior rig was working normally Monday (12/6) morning, and when I was running my second mouse, the wheel stopped moving to stimulus. Through conversations with Niccolo, it was brought to our attention that the code was unintentionally updated and this version has a a weird bug that freezes the visual stimulus randomly and non reproducibly. We have removed the update check in the batch script, but because the code had already updated, we got the same errors. After rolling the code back to the pre-updated version of 6.4.3 and 6.4.2 through deleting the iblrig folder, using git clone, and reinstalling the python, we are still unable to run the task as now we cannot "sync to Alyx" since it has been removed as an option when the GUI is open.

**Comment by nbonacchi** [comment]
Sync to Alyx should not preclude you from running the task. I'm not sure I understand the issue. Do you have a stacktrace of the error?

FYI: that pybpod module will be deprecated in the future

**Comment by srhaiken** [comment]
Traceback (most recent call last):  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\_iblrig_tasks_trainingChoiceWorld.py", line 13, in <module>    from iblrig.bpod_helper import BpodMessageCreator  File "C:\iblrig\iblrig\bpod_helper.py", line 12, in <module>    import iblrig.params as params  File "C:\iblrig\iblrig\params.py", line 15, in <module>    import iblrig.alyx as alyx  File "C:\iblrig\iblrig\alyx.py", line 10, in <module>    import ibllib.io.params as lib_paramsModuleNotFoundError: No module named 'ibllib.io.params'Traceback (most recent call last):  File "C:\iblrig\scripts\create_session.py", line 8, in <module>    import ibllib.io.params as paramsModuleNotFoundError: No module named 'ibllib.io.params'Traceback (most recent call last):  File "C:\iblrig\scripts\bpod_lights.py", line 7, in <module>    import iblrig.params as params  File "C:\iblrig\iblrig\params.py", line 15, in <module>    import iblrig.alyx as alyx  File "C:\iblrig\iblrig\alyx.py", line 10, in <module>    import ibllib.io.params as lib_paramsModuleNotFoundError: No module named 'ibllib.io.params'

**Comment by nbonacchi** [comment]
Looks like the installation did not complete properly. Are you sure no red errors appeared while installing?

**Comment by srhaiken** [comment]
We did another reinstallation and that fixed the syncing to Alyx issue, but we are still getting errors when trying to run the task even though there are no red errors while installing. 

It's trying to do: 2021-12-07 15:01:13.57 INFO     [registration.py:160] creating session for C:\iblrig_data\Subjects\5438\2021-10-07\002

And we get this:
File "C:\Users\Quinn\Anaconda3\envs\iblenv\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
stderr;2021-12-07 15:02:03.831784;;|Different project data hashes:
da99c4652798d6041b693caacdfa33b1f74de1a7194603602a98f2f389e7e6f6
7f8c526a50e7b4038cd6f42df9ef31943bd80ba4bb36923d02b51e1bc37f94d3
