### ISSUE TITLE
Error at opening

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#38]
```
PS C:\IBL_root> .\pybpod.bat
Finding pybpod folder...
Activating pybpod-environment...
Launching pybpod...
GUI
libpng warning: iCCP: known incorrect sRGB profile
17/07/2018 01:29:53 | WARNING | 12048 | pyforms_generic_editor.plugins.loader | install_plugins | Skiping bad plugin: No module named 'pybranch'
Traceback (most recent call last):
  File "c:\ibl_root\pybpod\pyforms-generic-editor\pyforms_generic_editor\plugins\loader.py", line 48, in install_plugins
    m = importlib.import_module(plugin_name)
  File "C:\Users\IBL\AppData\Local\Continuum\anaconda3\envs\pybpod-environment\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
ImportError: No module named 'pybranch'
creating treenode
libpng warning: iCCP: known incorrect sRGB profile
LOADING SUBJECT ALYX
```

**Comment by nbonacchi** [comment]
You can ignore that error...
