### ISSUE TITLE
2. Copy scripts (branch: none)

### ISSUE THREAD

**Issue by nbonacchi** [int-brain-lab/iblrig#385]

**Comment by nbonacchi** [comment]
After some detective work here are all the issues that should be closed regarding copy issues from behavior/ephys/video PCs:

https://github.com/int-brain-lab/iblrig/issues/401
https://github.com/int-brain-lab/iblscripts/issues/25
https://github.com/int-brain-lab/iblenv/issues/10
https://github.com/int-brain-lab/iblenv/issues/66
https://github.com/int-brain-lab/ibllib/issues/451

Let's centralize things here.

**Comment by micheleangelofabbri** [comment]
Additional troubleshooting performed on 2022-03-14 on the videoPC at CCU. The weird bug we were experiencing during a session folder rename process, where the session folder was being copied into another existing session folder instead of overwriting it; is apparently the default behavior of shutil.move - https://docs.python.org/3.8/library/shutil.html#shutil.move
```
shutil.move(src, dst, copy_function=copy2)
    Recursively move a file or directory (src) to another location (dst) and return the destination.
    If the destination is an existing directory, then src is moved inside that directory. ...
```

All changes that were made can be seen here - https://github.com/int-brain-lab/ibllib/commits/copyScript

The videoPC at CCU was left on the copyScript branch in order to deal with a few more real world tests.

**Comment by micheleangelofabbri** [comment]
On 2022-04-06, Guido attempted to run the transfer script and ran into an error:
```
(iblenv) PS>python .\transfer_video_session.py
LOCAL: D:\iblrig_data\Subjects
REMOTE: \\iblserver.champalimaud.pt\ibldata\Subjects
Found session: D:\iblrig_data\Subjects\ZFM-03059\2022-03-29\001
Found session: D:\iblrig_data\Subjects\ZFM-03059\2022-03-31\001
Found session: D:\iblrig_data\Subjects\ZFM-03059\2022-04-01\001
Found session: D:\iblrig_data\Subjects\ZFM-03059\2022-04-04\002
Found session: D:\iblrig_data\Subjects\ZFM-03059\2022-04-05\001
Found session: D:\iblrig_data\Subjects\ZFM-03059\2022-04-06\001
Found session: D:\iblrig_data\Subjects\ZFM-03323\2022-04-05\002
Found session: D:\iblrig_data\Subjects\ZFM-03323\2022-04-06\001
Found session: D:\iblrig_data\Subjects\ZFM-03324\2022-04-01\002
Which session number to use? Options: 2 or [s]kip/[h]elp/[e]xit> 2
Warning: session path D:\iblrig_data\Subjects\ZFM-03324\2022-04-01\002 already exists.
Would you like to move D:\iblrig_data\Subjects\ZFM-03324\2022-04-01\002 to a backup directory? [y/N]y
Traceback (most recent call last):
  File "C:\Users\IBLvideo\Anaconda3\envs\iblenv\lib\shutil.py", line 566, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'D:\\iblrig_data\\Subjects\\ZFM-03324\\2022-04-01\\002' -> 'D:\\iblrig_data\\Subjects\\ZFM-03324\\2022-04-01\\002'
```

During handling of the above exception, another exception occurred:
```
Traceback (most recent call last):
  File ".\transfer_video_session.py", line 24, in <module>
    confirm_video_remote_folder(local_folder=args.local, remote_folder=args.remote, force=args.force)
  File "c:\ibllib\ibllib\pipes\misc.py", line 376, in confirm_video_remote_folder
    session_path = rename_session(session_path, new_number=resp)
  File "c:\ibllib\ibllib\pipes\misc.py", line 136, in rename_session
    shutil.move(str(session_path), str(new_session_path))
  File "C:\Users\IBLvideo\Anaconda3\envs\iblenv\lib\shutil.py", line 580, in move
    copy_function(src, real_dst)
  File "C:\Users\IBLvideo\Anaconda3\envs\iblenv\lib\shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\IBLvideo\Anaconda3\envs\iblenv\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\iblrig_data\\Subjects\\ZFM-03324\\2022-04-01\\002'
```

Note, `D:\iblrig_data\Subjects\ZFM-03324\2022-04-01\002` did NOT exist.

**Comment by micheleangelofabbri** [comment]
On 2022-04-18, Laura reported a problem with the transfer of video files. The error that was presented:
```
FileNotFoundError: [WinError 2] The system cannot file the file specified: 'D:\\iblrig_data\\Subjects\\ZMF-03841\\2022-03-22\\001\\transfer_me.flag
```
The traceback shows that this came from a call to `flag_file.unlink()` in the `confirm_video_remote_folder` function of `ibllib/pipes/misc.py`. This call is intended to remove the `transfer_me.flag` file from the local videoPC after a transfer has completed. Currently there is no try/except to catch an OS errors or logic to handle the situation when the file is missing.

To get the files transferring again:
* I added the `transfer_me.flag` to several session folders that were lacking the file. These were folders listed in the `ibl_local_transfers` json file within the `APPDATA` windows user directory. 
* I then restarted the script and monitored the progress for two sessions before leaving the lab.

Note: another possible solution may have been to simply remove the `ibl_local_transfers` json file and restart the transfers again.

The initial cause of why the transfers were in such a weird state is currently unknown. Possibilities include some kind of manual intervention, an unaccounted for edge case, or the script failing at some unexpected point. Writing up the additional try/except mentioned earlier and taking into account this type of edge case will be the first step in narrowing down what caused the problem in the first place.

**Comment by micheleangelofabbri** [comment]
On 2022-04-19, it was reported that the same error was occurring:
```
FileNotFoundError: [WinError 2] The system cannot file the file specified: 'D:\\iblrig_data\\Subjects\\ZMF-#####\\2022-##-##\\001\\transfer_me.flag
```

Removing the `ibl_local_transfers` json file and restarting the transfers again seems to have been the resolution. Attached are the full logs of the successful transfer.

[2022-04-19_videoPC_transfer_log.txt](https://github.com/int-brain-lab/iblrig/files/8521314/2022-04-19_videoPC_transfer_log.txt)

**Comment by micheleangelofabbri** [comment]
spinnakerSDK and python packages v2.7.0.128 now running on CCU ephys videoPC with python v3.8 by utilizing the following software:
- [Latest Python Spinnaker](https://flir.app.boxcn.net/v/SpinnakerSDK/folder/73501875299)
- [Latest Spinnaker Full SDK](https://flir.app.boxcn.net/v/SpinnakerSDK/folder/73503062578)

rsync/copyScript branch has been integrated into ibllib and iblscripts
