### ISSUE TITLE
Video transfer script update

### ISSUE THREAD

**Issue by micheleangelofabbri** [int-brain-lab/iblrig#401]
Collection of troubleshooting steps taken to improve the video transfers on the VideoPC. This post is a summary of two days worth of troubleshooting.

2022-02-22 - VideoPC at CCU had its `ibllib` branch switched to [copyScript](https://github.com/int-brain-lab/ibllib/tree/copyScript), the following commands and error logs were generated:
```
(iblenv) PS>cd C:\iblscripts\deploy\videopc\
(iblenv) PS>python .\transfer_video_session.py
Where's your LOCAL 'Subjects' data folder? [default: D:\iblrig_data\Subjects]:
Where's your REMOTE 'Subjects' data folder? [default: \\iblserver.champalimaud.pt\ibldata\Subjects]:
How many probes are you using? [default: 2]:
What's the type of PROBE 00? ([3A] | 3B)> 3B
What's the type of PROBE 01? ([3A] | 3B)> 3B
Created C:\Users\IBLvideo\AppData\Roaming\.ephyspc_params
{'DATA_FOLDER_PATH': 'D:\\iblrig_data\\Subjects', 'REMOTE_DATA_FOLDER_PATH': '\\\\iblserver.champalimaud.pt\\ibldata\\Subjects', 'PROBE_TYPE_00': '3B', 'PROBE_TYPE_01': '3B'}
LOCAL: D:\iblrig_data\Subjects
REMOTE: \\iblserver.champalimaud.pt\ibldata\Subjects

Found session: D:\iblrig_data\Subjects\ZFM-03447\2022-02-19\002
Which session number to use? Options: 1 or [s]kip/[e]xit1
Which session number to use? Options: 1 or [s]kip/[e]xit1
Which session number to use? Options: 1 or [s]kip/[e]xit 1
Which session number to use? Options: 1 or [s]kip/[e]xit1
Which session number to use? Options: 1 or [s]kip/[e]xit001
Warning: session path D:\iblrig_data\Subjects\ZFM-03447\2022-02-19\001 already exists.
Overwrite? [y/N]y
D:\iblrig_data\Subjects\ZFM-03447\2022-02-19\002 --> renamed to:
D:\iblrig_data\Subjects\ZFM-03447\2022-02-19\001
Preventing Windows from going to sleep
Attempting to copy:
D:\iblrig_data\Subjects\ZFM-03447\2022-02-19\001\raw_video_data
--> \\iblserver.champalimaud.pt\ibldata\Subjects\ZFM-03447\2022-02-19\001\raw_video_data
Copying all files:
D:\iblrig_data\Subjects\ZFM-03447\2022-02-19\001\raw_video_data
--> \\iblserver.champalimaud.pt\ibldata\Subjects\ZFM-03447\2022-02-19\001\raw_video_data
Traceback (most recent call last):
  File ".\transfer_video_session.py", line 24, in <module>
    confirm_video_remote_folder(local_folder=args.local, remote_folder=args.remote, force=args.force)
  File "c:\ibllib\ibllib\pipes\misc.py", line 341, in confirm_video_remote_folder
    transfer_folder(Path(session_path) / 'raw_video_data', Path(remote_session_path) / 'raw_video_data', force=force)
  File "c:\ibllib\ibllib\pipes\misc.py", line 151, in transfer_folder
    shutil.copytree(src, dst, dirs_exist_ok=True, copy_function=copy_with_check)
TypeError: copytree() got an unexpected keyword argument 'dirs_exist_ok'
(iblenv) PS>python .\transfer_video_session.py
LOCAL: D:\iblrig_data\Subjects
REMOTE: \\iblserver.champalimaud.pt\ibldata\Subjects

Found session: D:\iblrig_data\Subjects\ZFM-03447\2022-02-19\002
Which session number to use? Options: 1 or [s]kip/[e]xite
Exiting.  No files transferred.
(iblenv) PS>python .\transfer_video_session.py
LOCAL: D:\iblrig_data\Subjects
REMOTE: \\iblserver.champalimaud.pt\ibldata\Subjects

Found session: D:\iblrig_data\Subjects\ZFM-03447\2022-02-19\002
Which session number to use? Options: 001 or [s]kip/[e]xit> 001
Warning: session path D:\iblrig_data\Subjects\ZFM-03447\2022-02-19\001 already exists.
Overwrite? [y/N]y
D:\iblrig_data\Subjects\ZFM-03447\2022-02-19\002 --> renamed to:
D:\iblrig_data\Subjects\ZFM-03447\2022-02-19\001
Preventing Windows from going to sleep
Attempting to copy:
D:\iblrig_data\Subjects\ZFM-03447\2022-02-19\001\raw_video_data
--> \\iblserver.champalimaud.pt\ibldata\Subjects\ZFM-03447\2022-02-19\001\raw_video_data
Copying all files:
D:\iblrig_data\Subjects\ZFM-03447\2022-02-19\001\raw_video_data
--> \\iblserver.champalimaud.pt\ibldata\Subjects\ZFM-03447\2022-02-19\001\raw_video_data
All files copied
Traceback (most recent call last):
  File ".\transfer_video_session.py", line 24, in <module>
    confirm_video_remote_folder(local_folder=args.local, remote_folder=args.remote, force=args.force)
  File "c:\ibllib\ibllib\pipes\misc.py", line 347, in confirm_video_remote_folder
    flag_file.unlink()
  File "C:\Users\IBLvideo\Anaconda3\envs\iblenv\lib\pathlib.py", line 1309, in unlink
    self._accessor.unlink(self)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'D:\\iblrig_data\\Subjects\\ZFM-03447\\2022-02-19\\001\\transfer_me.flag'
(iblenv) PS>python .\transfer_video_session.py
LOCAL: D:\iblrig_data\Subjects
REMOTE: \\iblserver.champalimaud.pt\ibldata\Subjects

Found session: D:\iblrig_data\Subjects\ZFM-03447\2022-02-19\002
Which session number to use? Options: 001 or [s]kip/[e]xit> 001
Warning: session path D:\iblrig_data\Subjects\ZFM-03447\2022-02-19\001 already exists.
Overwrite? [y/N]y
D:\iblrig_data\Subjects\ZFM-03447\2022-02-19\002 --> renamed to:
D:\iblrig_data\Subjects\ZFM-03447\2022-02-19\001
Preventing Windows from going to sleep
Attempting to copy:
D:\iblrig_data\Subjects\ZFM-03447\2022-02-19\001\raw_video_data
--> \\iblserver.champalimaud.pt\ibldata\Subjects\ZFM-03447\2022-02-19\001\raw_video_data
All files already copied, use force=True to re-copy
Traceback (most recent call last):
  File ".\transfer_video_session.py", line 24, in <module>
    confirm_video_remote_folder(local_folder=args.local, remote_folder=args.remote, force=args.force)
  File "c:\ibllib\ibllib\pipes\misc.py", line 347, in confirm_video_remote_folder
    flag_file.unlink()
  File "C:\Users\IBLvideo\Anaconda3\envs\iblenv\lib\pathlib.py", line 1309, in unlink
    self._accessor.unlink(self)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'D:\\iblrig_data\\Subjects\\ZFM-03447\\2022-02-19\\001\\transfer_me.flag'
```

Other noted behavior:
* script tries to unlink the `transfer_me.flag` file that is not there after a rename
* video files appear to transfer, but still throws errors
* Finally the local session directory structure gets rearranged
  * `subject/date/002` was moved to `subject/date/001` instead of subject/date overwriting the 001 session
  * `exist_dirs_ok` flag errors out due to python incompatibility (v3.7 vs v3.8+)

2022-02-25 - Another troubleshooting session in front of the VideoPC with the following commands being run to set up a "clean environment":
* `conda deactivate`
* `conda create --name iblenv_bkup --clone iblenv`
* `conda remove --name iblenv --all`
* `conda create -n iblenv python=3.8`
* `conda activate iblenv`
* find or [download](https://flir.app.boxcn.net/v/SpinnakerSDK/folder/73501875299) the latest spinnakerSDK
* unzip and navigate to that folder
* `pip install spinnaker_python-2.6.0.156-cp38-cp38-win_amd64.whl`
* (there may be another driver that is required to be installed at this point)
* `cd C:\`
* `git clone https://github.com/int-brain-lab/ibllib.git`
* `cd C:\ibllib`
* `git checkout copyScript`
* `pip install -e .` (the checkout can also be done after installing)
* `pip freeze/list` to ensure only ibllib and spinnaker are installed in the conda env iblenv
* `cd C:\iblscripts\deploy\videopc\`
* `git fetch; git pull` just to make sure it's the latest master
* `python .\transfer_video_session.py`

After these commands were issued, there was a fair amount of trial and error with Miles and myself trying to figure out some of the unexpected behavior that persisted, i.e. local directory structure getting rearranged:

> D:\iblrig_data\Subjects\ZFM-03447\2022-02-19>tree /F
Folder PATH listing for volume Data1
Volume serial number is BC36-258F
D:.
└───001
    ├───002
    │   │   transfer_me.flag
    │   │
    │   └───raw_video_data
    │           _iblrig_leftCamera.frameData.bin
    │           _iblrig_leftCamera.raw.avi
    │
    └───raw_video_data
            _iblrig_leftCamera.frameData.bin

A local file `C:/Users/User/AppData/Roaming/.ibl_local_transfers` was also deleted between git pulls of newer commits and the rerunning of `(iblenv) C:\iblscripts\deploy\videopc>python transfer_video_session.py`

This last log file is showing a successful transfer. This was the impetus to leave the VideoPC on the `copyScript` branch:
```
(iblenv) C:\iblscripts\deploy\videopc>python transfer_video_session.py
LOCAL: D:\iblrig_data\Subjects
REMOTE: \\iblserver.champalimaud.pt\ibldata\Subjects

Found session: D:\iblrig_data\Subjects\ZFM-03059\2022-02-25\003
2022-02-25 16:55:55.551 INFO     [misc.py:340] Added to transfers list:
('D:/iblrig_data/Subjects/ZFM-03059/2022-02-25/003', '//iblserver.champalimaud.pt/ibldata/Subjects/ZFM-03059/2022-02-25/003')

Found session: D:\iblrig_data\Subjects\ZFM-03324\2022-02-23\001
Which session number to use? Options: 2 or [s]kip/[h]elp/[e]xit> s

Found session: D:\iblrig_data\Subjects\ZFM-03324\2022-02-23\002
Which session number to use? Options: 2 or [s]kip/[h]elp/[e]xit> s

Found session: D:\iblrig_data\Subjects\ZFM-03324\2022-02-24\001
2022-02-25 16:56:20.411 INFO     [misc.py:340] Added to transfers list:
('D:/iblrig_data/Subjects/ZFM-03324/2022-02-24/001', '//iblserver.champalimaud.pt/ibldata/Subjects/ZFM-03324/2022-02-24/001')

Found session: D:\iblrig_data\Subjects\ZFM-03329\2022-02-23\001
2022-02-25 16:56:20.415 INFO     [misc.py:340] Added to transfers list:
('D:/iblrig_data/Subjects/ZFM-03329/2022-02-23/001', '//iblserver.champalimaud.pt/ibldata/Subjects/ZFM-03329/2022-02-23/001')

Found session: D:\iblrig_data\Subjects\ZFM-03329\2022-02-24\001
2022-02-25 16:56:20.419 INFO     [misc.py:340] Added to transfers list:
('D:/iblrig_data/Subjects/ZFM-03329/2022-02-24/001', '//iblserver.champalimaud.pt/ibldata/Subjects/ZFM-03329/2022-02-24/001')

Found session: D:\iblrig_data\Subjects\ZFM-03329\2022-02-25\001
Which session number to use? Options: 1 or [s]kip/[h]elp/[e]xit> s

Found session: D:\iblrig_data\Subjects\ZFM-03329\2022-02-25\002
Which session number to use? Options: 1 or [s]kip/[h]elp/[e]xit> s

Found session: D:\iblrig_data\Subjects\ZFM-03447\2022-02-19\002
Which session number to use? Options: 1 or [s]kip/[h]elp/[e]xit> s

Found session: D:\iblrig_data\Subjects\ZFM-03447\2022-02-25\001
2022-02-25 16:56:27.973 INFO     [misc.py:340] Added to transfers list:
('D:/iblrig_data/Subjects/ZFM-03447/2022-02-25/001', '//iblserver.champalimaud.pt/ibldata/Subjects/ZFM-03447/2022-02-25/001')
Preventing Windows from going to sleep
2022-02-25 16:56:27.975 INFO     [misc.py:352] Tranfering D:\iblrig_data\Subjects\ZFM-03059\2022-02-25\003\raw_video_data-->\\iblserver.champalimaud.pt\ibldata\Subjects\ZFM-03059\2022-02-25\003\raw_video_data
Attempting to copy:
D:\iblrig_data\Subjects\ZFM-03059\2022-02-25\003\raw_video_data
--> \\iblserver.champalimaud.pt\ibldata\Subjects\ZFM-03059\2022-02-25\003\raw_video_data
All files already copied, use force=True to re-copy
2022-02-25 16:56:27.983 INFO     [misc.py:358] Removing D:\iblrig_data\Subjects\ZFM-03059\2022-02-25\003\transfer_me.flag
2022-02-25 16:56:28.48 INFO     [misc.py:352] Tranfering D:\iblrig_data\Subjects\ZFM-03329\2022-02-23\001\raw_video_data-->\\iblserver.champalimaud.pt\ibldata\Subjects\ZFM-03329\2022-02-23\001\raw_video_data
Attempting to copy:
D:\iblrig_data\Subjects\ZFM-03329\2022-02-23\001\raw_video_data
--> \\iblserver.champalimaud.pt\ibldata\Subjects\ZFM-03329\2022-02-23\001\raw_video_data
Copying all files:
D:\iblrig_data\Subjects\ZFM-03329\2022-02-23\001\raw_video_data
--> \\iblserver.champalimaud.pt\ibldata\Subjects\ZFM-03329\2022-02-23\001\raw_video_data
All files copied
2022-02-25 16:57:30.133 INFO     [misc.py:358] Removing D:\iblrig_data\Subjects\ZFM-03329\2022-02-23\001\transfer_me.flag
2022-02-25 16:57:30.189 INFO     [misc.py:352] Tranfering D:\iblrig_data\Subjects\ZFM-03447\2022-02-25\001\raw_video_data-->\\iblserver.champalimaud.pt\ibldata\Subjects\ZFM-03447\2022-02-25\001\raw_video_data
Attempting to copy:
D:\iblrig_data\Subjects\ZFM-03447\2022-02-25\001\raw_video_data
--> \\iblserver.champalimaud.pt\ibldata\Subjects\ZFM-03447\2022-02-25\001\raw_video_data
Copying all files:
D:\iblrig_data\Subjects\ZFM-03447\2022-02-25\001\raw_video_data
--> \\iblserver.champalimaud.pt\ibldata\Subjects\ZFM-03447\2022-02-25\001\raw_video_data
All files copied
2022-02-25 17:00:57.528 INFO     [misc.py:358] Removing D:\iblrig_data\Subjects\ZFM-03447\2022-02-25\001\transfer_me.flag
Allowing Windows to go to sleep
```

**Comment by micheleangelofabbri** [comment]
Received reports from Guido this morning that despite the spinnaker driver being installed, they were running into the following error:
```
(iblenv) PS>python prepare_video_session.py ZFM-03324 --training
Traceback (most recent call last):
  File "prepare_video_session.py", line 14, in <module>
    import config_cameras as cams
  File "C:\iblscripts\deploy\videopc\config_cameras.py", line 16, in <module>
    SYSTEM = PySpin.System.GetInstance()
  File "C:\Users\IBLvideo\Anaconda3\envs\iblenv\lib\site-packages\PySpin\PySpin.py", line 35400, in GetInstance
    return _PySpin.System_GetInstance()
_PySpin.SpinnakerException: Spinnaker: System instance cannot be acquired. Could not load producer. Make sure that the environment variable FLIR_GENTL64_CTI_VS140 exists, and points to the location of the file FLIR_GenTL_v140.cti [-1012]
```

Being that this was completely preventing the usage of the ephys rig, a rollback the VideoPC changes: 
* `conda deactivate`
* `conda create --name iblenv38 --clone iblenv`
* `conda remove --name iblenv`
* deleted the `C:\Users\<win_username>\Anaconda3\envs\iblenv` folder
* `conda create --name iblenv --clone iblenv_bkup`
* retested the `python prepare_video_session.py` script
