### ISSUE TITLE
Updating NYU behavior rigs that were sitting on v6.4.2

### ISSUE THREAD

**Issue by micheleangelofabbri** [int-brain-lab/iblrig#402]
Issue is a summary of a slack thread that was hijacked on 2022-02-24. Julius at NYU had been holding off updating their rigs to v6.5.3, due to a failed update from 6.4.2 on a single rig that was never completed. 

2022-02-24: 
* "Might be worth noting that I'm at a detached head at version 6.4.2. I tried installing 6.5 on one of our 3 training rigs and it completely broke all functionality, so I didn't upgrade the other rigs to 6.5."
* Initial log file that was sent over:
```
(base) PS C:\iblrig> git status
HEAD detached at 6.5.2
nothing to commit, working tree clean
...
(base) PS C:\iblrig> python install.py
--->Cleaning up conda cache
& was unexpected at this time.
--->conda cache... OK
--->mamba not found
--->Installing mamba
& was unexpected at this time.
--->mamba installed... OK
INFO: Checking for dependencies:
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
[WinError 2] The system cannot find the file specified
SOMETHING IS WRONG: Bad! Bad install file!
INFO: iblrig installation EoF
```
* Teamviewer access to the machine was given
* updated iblrig version to v6.5.3 (the lazy way)
  * bakup `C:\iblrig`
  * `cd C:\`
  * `git clone https://github.com/int-brain-lab/iblrig.git`
  * `cd iblrig`
  * `git checkout tags/6.5.3`
* recreated the anaconda environments for `iblenv` and `ibllib` manually instead of using the install script, due to the command prompt of he computer repeatedly crashing, this was a non-starter as this was indicative of a larger issue of registry keys not getting cleaned up from a failed anaconda uninstall
* Running the following command corrected the registry key issue
  * `C:\Windows\System32\reg.exe DELETE "HKCU\Software\Microsoft\Command Processor" /v AutoRun /f`
  * https://stackoverflow.com/questions/66335300/cmd-crashes-with-exit-code-1-after-uninstalling-anaconda

2022-02-25:
* User performed some further, unspecified, troubleshooting on their end and attempted to perform a frame2TTL calibration on the rig, but received the following error:
```
Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_calibration_frame2TTL\_iblrig_calibration_frame2TTL.py", line 17, in <module>
    sph.start_screen_color()
  File "C:\iblrig_params\IBL\tasks\_iblrig_calibration_frame2TTL\session_params.py", line 53, in start_screen_color
    bonsai.start_screen_color()
  File "c:\iblrig\iblrig\bonsai.py", line 313, in start_screen_color
    subprocess.Popen([bns, wrkfl, editor, noboot])
  File "C:\Users\IBLuser\anaconda3\envs\iblenv\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\IBLuser\anaconda3\envs\iblenv\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

2022-02-27:
* remoted into the rig
* backed up the conda environment
* reran the install script, this time under the now functional windows command prompt
* iblrig software successfully installed, but ONE picked up the previous configuration that was set for openalyx
* requested that user open up command prompt, activate the ibllib conda environment, launch a python interpreter, and change the ONE base_url:
  * conda activate ibllib
  * python
  * from one.api import ONE
  * ONE(base_url='https://alyx.internationalbrainlab.org/')
* if that failed for some reason
  * delete the `C:\Users\<win_username>\AppData\Roaming\.one` directory
  * rerun those above commands
* as reported by the user, the rig is now fully functional

**Comment by micheleangelofabbri** [comment]
2022-02-25:
* An attempt was made to update a separate behavior PC by Julius; they were successful upgrading the local iblrig repo to v6.5.3, but then ran into an error with the `install.py` script:
```
INFO: Checking for dependencies:
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
Traceback (most recent call last):
  File "C:\Users\IBLuser\Anaconda3\Scripts\mamba-script.py", line 6, in <module>
    from mamba.mamba import main
  File "C:\Users\IBLuser\Anaconda3\lib\site-packages\mamba\mamba.py", line 53, in <module>
    from mamba.utils import get_index, to_package_record_from_subjson, _supplement_index_with_system
  File "C:\Users\IBLuser\Anaconda3\lib\site-packages\mamba\utils.py", line 7, in <module>
    from .FastSubdirData import FastSubdirData
  File "C:\Users\IBLuser\Anaconda3\lib\site-packages\mamba\FastSubdirData.py", line 23, in <module>
    from conda._vendor.auxlib.ish import dals
ModuleNotFoundError: No module named 'conda._vendor.auxlib'
Command '['mamba', 'list', '--json']' returned non-zero exit status 1.
```
* the traceback may indicate some issue with the conda/mamba install, this will be looked into further once the user gives more information and a timeframe for another teamviewer session

**Comment by micheleangelofabbri** [comment]
2022-03-05:
Two training rigs needed to be looked at and I was able to get both updated to v6.5.3 of the iblrig software. A few noteworthy points:

### behavior rig 2 (Computer name IBLRIG005):
- completely uninstalled/reinstalled latest anaconda
- backed up iblrig and iblrig_params folders
- used git to clone the iblrig repo
- checked out 6.5.3 release
- ran install script
- I found the `Z:` network drive mapped to `\\#.#.#.#\ibldata`, but for the software to function correctly, that target needs to be mapped to the `Y:` network drive
  - mapped the `Y:` network drive to `\\#.#.#.#\ibldata`
  - `Z:` network drive mapping left active as well, in case there are other references to it that I am unaware of
- successfully ran habituationChoiceWorld as test_user on test_mouse to validate install

### behavior rig 1 (Computer name IBLRIG006):
- completely uninstalled/reinstalled latest anaconda
- backed up iblrig and iblrig_params folders
- used git to clone the iblrig repo
- checked out 6.5.3 release
- ran install script
- I found a slightly stranger situation for the networked mapped drives here
  - `Y:` network drive
    - Was mapped to `\\omitted\server`
    - Is now mapped to `\\#.#.#.#\ibldata`
  - `Z:` network drive was similarly mapped to `\\#.#.#.#\ibldata` and I left as is in case there are other references to it that I am unaware of
  - `V:` network drive now pointing to `\\omitted\server`, this is the location that `Y:` was previously mapped to
  - `W:` network drive untouched, pointing to `\\omitted\server3`
- successfully ran habituationChoiceWorld as test_user on test_mouse to validate install
