### ISSUE TITLE
No module named 'ibllib.graphic" 

### ISSUE THREAD

**Issue by icullen87** [int-brain-lab/iblrig#427]
Recently installed the newest version of IBL onto a separate user account with a separate conda account and environment. So all needed files are under C:\Users\Isabelle, since we have old working files under C:\iblrig. When I open PyBpod and try to run any task, this error immediately comes up. I am running this in the iblrig env, and have the ibllib installed. I've changed the user settings to direct the project to my specific user, but I have not had any success yet with getting this to work. 

**To Reproduce**
1. Open IBL PyBpod like normal 
2. Select local user
3. Run task

**Screenshots**
Traceback (most recent call last):
  File "C:\Users\Isabelle\iblrig\scripts\bpod_lights.py", line 7, in <module>
    import iblrig.params as params
  File "C:\iblrig\iblrig\params.py", line 12, in <module>
    from ibllib.graphic import strinput
ModuleNotFoundError: No module named 'ibllib.graphic'
File "C:\Users\Isabelle\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\_iblrig_tasks_trainingChoiceWorld.py", line 7, in <module>
    import iblrig.bonsai as bonsai
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 843, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "C:\iblrig\iblrig\bonsai.py", line 15, in <module>
    import iblrig.path_helper as ph
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 843, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "C:\iblrig\iblrig\path_helper.py", line 12, in <module>
    import iblrig.params as params
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 843, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "C:\iblrig\iblrig\params.py", line 12, in <module>
    from ibllib.graphic import strinput
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 843, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "C:\Users\Isabelle\anaconda3\envs\iblrig\lib\site-packages\ibllib\graphic.py", line 10, in <module>
    for line in traceback.format_stack():
C:\Users\Isabelle\anaconda3\envs\iblrig\lib\site-packages\ibllib\graphic.py:13: DeprecationWarning: ibllib.graphic has been deprecated. See stack above
  warnings.warn('ibllib.graphic has been deprecated. '
Traceback (most recent call last):
  File "C:\Users\Isabelle\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\_iblrig_tasks_trainingChoiceWorld.py", line 7, in <module>
    import iblrig.bonsai as bonsai
  File "C:\iblrig\iblrig\bonsai.py", line 15, in <module>
    import iblrig.path_helper as ph
  File "C:\iblrig\iblrig\path_helper.py", line 12, in <module>
    import iblrig.params as params
  File "C:\iblrig\iblrig\params.py", line 12, in <module>
    from ibllib.graphic import strinput
ImportError: cannot import name 'strinput' from 'ibllib.graphic' (C:\Users\Isabelle\anaconda3\envs\iblrig\lib\site-packages\ibllib\graphic.py)
Traceback (most recent call last):
  File "C:\Users\Isabelle\iblrig\scripts\bpod_lights.py", line 7, in <module>
    import iblrig.params as params
  File "C:\iblrig\iblrig\params.py", line 12, in <module>
    from ibllib.graphic import strinput
ModuleNotFoundError: No module named 'ibllib.graphic'
Traceback (most recent call last):
  File "C:\Users\Isabelle\iblrig\scripts\create_session.py", line 11, in <module>
    import iblrig.path_helper as ph
  File "C:\iblrig\iblrig\path_helper.py", line 11, in <module>
    from ibllib.io import raw_data_loaders as raw
ModuleNotFoundError: No module named 'ibllib.io'

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by icullen87** [comment]
If anyone else experiences this problem, the issue is the ibllib library location is hard coded to be C:\\iblrig, and if you have it on another location other than that, it won't work
