### ISSUE TITLE
The last state machine sent was not acknowledged ...

### ISSUE THREAD

**Issue by bimac** [int-brain-lab/iblrig#541]
```
2023-10-31 11:31:20.334 INFO     [base_choice_world.py:  165]   Starting trial: 40
2023-10-31 11:31:20.334 INFO     [base_choice_world.py:  165]   Starting trial: 40
2023-10-31 11:31:20.334 INFO     [base_choice_world.py:  170]   Sending state machine to bpod
2023-10-31 11:31:20.334 INFO     [base_choice_world.py:  170]   Sending state machine to bpod
2023-10-31 11:31:20.334 INFO     [bpod_base.py:  244]   Sending state machine
2023-10-31 11:31:20.824 INFO     [base_choice_world.py:  179]   running state machine
2023-10-31 11:31:20.824 INFO     [base_choice_world.py:  179]   running state machine
2023-10-31 11:31:20.824 INFO     [bpod_base.py:  283]   Running state machine, trial 42
Traceback (most recent call last):
  File "C:\iblrigv8\iblrig_tasks\_iblrig_tasks_biasedChoiceWorld\task.py", line 12, in <module>
    sess.run()
  File "C:\iblrigv8\iblrig\base_tasks.py", line 391, in run
    self._run()  # runs the specific task logic ie. trial loop etc...
  File "C:\iblrigv8\iblrig\base_choice_world.py", line 634, in _run
    super(ActiveChoiceWorldSession, self)._run()
  File "C:\iblrigv8\iblrig\base_choice_world.py", line 180, in _run
    self.bpod.run_state_machine(sma)  # Locks until state machine 'exit' is reached
  File "C:\iblrigv8\venv\lib\site-packages\pybpodapi\bpod\bpod_base.py", line 292, in run_state_machine
    raise BpodErrorException('Error: The last state machine sent was not acknowledged by the Bpod device.', self)
pybpodapi.exceptions.bpod_error.BpodErrorException: ('Error: The last state machine sent was not acknowledged by the Bpod device.', <iblrig.hardware.Bpod object at 0x000001335E0E1E40>)
2023-10-31 11:33:01.314 INFO     [bpod_base.py:  132]   Starting Bpod
```

![image](https://github.com/int-brain-lab/iblrig/assets/16573396/bf73278c-5ac4-40d0-9216-77149c4b52e0)

**Comment by bimac** [comment]
mainen rig #2, ZFM-06271, 2023-10-31, session 001

**Comment by bimac** [comment]
potentially an issue fixed with #539 - waiting for user feedback

**Comment by bimac** [comment]
issue was not fixed

**Comment by bimac** [comment]
check potential micros() overflow
