### ISSUE TITLE
Bugs in task chaining

### ISSUE THREAD

**Issue by samupicard** [int-brain-lab/iblrig#568]
Two possibly related bugs when using the 'append' functionality on two consecutive biasedChoiceWorld tasks
- [x] when selecting the append button in the GUI, the protocol starts, but the online plots don't show up
- [x] the data transfer script throws an error, see below

```
2023-12-04 15:02:59.494 CRITICAL [commands.py:  270]   1, C:\iblrigv8_data\cortexlab\Subjects\SP046\2023-11-29\001
2023-12-04 15:02:59.504 INFO     [transfer_experiments.py:  194]   1, C:\iblrigv8_data\cortexlab\Subjects\SP046\2023-11-29\001
microphone
_iblrig_tasks_biasedChoiceWorld
_iblrig_tasks_biasedChoiceWorld
Traceback (most recent call last):
  File "C:\Users\IBL\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\IBL\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\iblrigv8\venv\Scripts\transfer_data.exe\__main__.py", line 7, in <module>
  File "C:\iblrigv8\iblrig\commands.py", line 86, in transfer_data_cli
    transfer_data(**vars(args), interactive=True)
  File "C:\iblrigv8\iblrig\commands.py", line 271, in transfer_data
    copier.run(number_of_expected_devices=number_of_expected_devices)
  File "C:\iblrigv8\iblrig\transfer_experiments.py", line 195, in run
    self.copy_collections()
  File "C:\iblrigv8\iblrig\transfer_experiments.py", line 298, in copy_collections
    status = self._copy_collections()
  File "C:\iblrigv8\iblrig\transfer_experiments.py", line 269, in _copy_collections
    collections = set(session_params.get_collections(exp_pars).values())
TypeError: unhashable type: 'list'
```

**Comment by samupicard** [comment]
Have you been able to look into this @bimac @k1o0 ?

**Comment by k1o0** [comment]
Not yet, but I will look at the second problem this week while I update the copy script routine.

**Comment by samupicard** [comment]
@bimac I believe the task chaining plotting bug is still there. Using separate sessions instead is causing a real headache when it comes to copying data correctly. When can we expect this to be resolved?

**Comment by samupicard** [comment]
@k1o0 atm on our mesoscope behavior rig the transfer_data script still throws the same error when trying to transfer chained protocols, but perhaps it's because the bug fix is only on videopc branch and hasn't been pushed to the iblrigv8 branch yet? Should I switch to videopc branch?
