### ISSUE TITLE
task fails with error after 1h

### ISSUE THREAD

**Issue by bimac** [int-brain-lab/iblrig#676]
```
11:27:27 Starting trial: 741
Traceback (most recent call last):
  File "C:\iblrigv8\venv\lib\site-packages\iblrig_custom_tasks\samuel_cuedBiasedChoiceWorld\task.py", line 214, in <module>
sess.run()
  File "C:\iblrigv8\iblrig\base_tasks.py", line 497, in run
self._run()  # runs the specific task logic ie. trial loop etc...
  File "C:\iblrigv8\iblrig\base_choice_world.py", line 638, in _run
super()._run()
  File "C:\iblrigv8\iblrig\base_choice_world.py", line 187, in _run
self.trial_completed(self.bpod.session.current_trial.export())
  File "C:\iblrigv8\iblrig\base_choice_world.py", line 668, in trial_completed
    outcome = next(k for k in raw_outcome if raw_outcome[k])
StopIteration

Subprocess finished.
```

SP054 on cortexlab rig4

[_ibl_log.info-acquisition.log](https://github.com/user-attachments/files/15788158/_ibl_log.info-acquisition.2.log)
[_iblrig_taskData.raw.zip](https://github.com/user-attachments/files/15788203/_iblrig_taskData.raw.zip)

**Comment by oliche** [comment]
We added some logging and secured the port. Let's wait for it to happen again with more information.
