### ISSUE TITLE
can't stop flush_water

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#83]
in several tasks (even with flush_water), python crashes when trying to 'stop'

e.g.
```
Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_misc_flush_water\_iblrig_misc_flush_water.py", line 17, in <module>
    bpod = Bpod()
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\pybpodapi\bpod\bpod_io.py", line 28, in __init__
    super(BpodIO,self).__init__(serial_port, sync_channel, sync_mode)
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\pybpodapi\bpod\bpod_com_protocol.py", line 44, in __init__
    if self.serial_port: self.open()
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\pybpodapi\bpod\bpod_com_protocol.py", line 48, in open
    super(BpodCOMProtocol, self).open()
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\pybpodapi\bpod\bpod_base.py", line 133, in open
    self._bpodcom_connect(self.serial_port, self.baudrate)
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\pybpodapi\bpod\bpod_com_protocol.py", line 67, in _bpodcom_connect
    self._arcom = ArCOM().open(serial_port, baudrate, timeout)
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\pybpodapi\com\arcom.py", line 98, in open
    self.serial_object = serial.Serial(serial_port, baudrate=baudrate, timeout=timeout)
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\serial\serialutil.py", line 240, in __init__
    self.open()
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM5': PermissionError(13, 'Access is denied.', None, 5)
C:\iblrig_params\IBL\experiments\_iblrig_misc\setups\flush_water\sessions\201901~1\20190122-153303.csv - The process cannot access the file because it is being used by another process.
C:\iblrig_params\IBL\experiments\_iblrig_misc\setups\flush_water\sessions\201901~1 - The process cannot access the file because it is being used by another process.
```

This causes Bpod to continue running the task, showing orange/green colors and flushing water, even though the pybpod GUI shows that the task was stopped.

**Comment by nbonacchi** [comment]
Looks like a COM port with Bpod issue... Like you pressed Stop, start and stop again too fast. or Stop but not stop trial. top stop the flush actually one needs to press both as the flush is just a state with a very large valve open time, so the state machine is in the middle of a trial waiting for a timer to elapse. Pressing stopand then stop trial will exit from that.

Protip: Whenever there is a lack of response from PyBpod to do something, try focusing on terminal and pressing enter... For some reason this happens almost every time after having ran a task...
