### ISSUE TITLE
mouse weigt value not accepted

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#84]
when typing 29,06, pybpod says it wants a floating point value. however, for 29.06 trainingChoiceWorld crashes on the following

```
Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\_iblrig_tasks_trainingChoiceWorld.py", line 20, in <module>
    sph = SessionParamHandler(task_settings, user_settings)
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\session_params.py", line 100, in __init__
    self.REWARD_AMOUNT = self._init_reward_amount()
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\session_params.py", line 401, in _init_reward_amount
    previous_weight_factor = self.LAST_SETTINGS_DATA['SUBJECT_WEIGHT'] / 25
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

**Comment by nbonacchi** [comment]
The default separator for floating point values is a 'point'. In EU we like using commas for floating points and points for thousands separator, 1.000,00 vs 1,000.0 US

The value 29.06 was accepted but the weight factor was not computed because it found a None in the previous session weight information. The only way this might happen is if you pressed 'Cancel' when prompted for the weight in the previous session.
I'll add a check to not allow that.
