### ISSUE TITLE
flush water can't be stopped

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#85]
On two rigs (after updating to 3.5.1), clicking 'stop' in flush water does not turn the state machine off (it stays green/orange) and water keeps flowing. 

```
stderr;2019-01-23 15:49:18.457037;;|No Subjects selected
|;;
Starting trial:  1
stderr;2019-01-23 15:50:03.998522;;|Different project data hashes:
7c55f8eb4895270b0a4fbb4ac8ba0fdb77fa0e70c861b8cf0d593e880725556c
007c7b7a122b5ca7cb8a2c3e6381b348b18ba878b42bfc7c0ddb9eba46970991
|;;
stderr;2019-01-23 15:50:03.999493;;|Run protocol cannot be executed because project is not saved.
|;;
Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_misc_flush_water\_iblrig_misc_flush_water.py", line 17, in <module>
    bpod = Bpod()
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\pybpodapi\bpod\bpod_io.py", line 28, in __init__
    super(BpodIO,self).__init__(serial_port, sync_channel, sync_mode)
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\pybpodapi\bpod\bpod_com_protocol.py", line 44, in __init__
    if self.serial_port: self.open()
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\pybpodapi\bpod\bpod_com_protocol.py", line 48, in open
    super(BpodCOMProtocol, self).open()
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\pybpodapi\bpod\bpod_base.py", line 133, in open
    self._bpodcom_connect(self.serial_port, self.baudrate)
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\pybpodapi\bpod\bpod_com_protocol.py", line 67, in _bpodcom_connect
    self._arcom = ArCOM().open(serial_port, baudrate, timeout)
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\pybpodapi\com\arcom.py", line 98, in open
    self.serial_object = serial.Serial(serial_port, baudrate=baudrate, timeout=timeout)
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\serial\serialutil.py", line 240, in __init__
    self.open()
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM5': PermissionError(13, 'Access is denied.', None, 5)
C:\iblrig_params\IBL\experiments\_iblrig_misc\setups\flush_water\sessions\201901~1\20190123-154924.csv - The process cannot access the file because it is being used by another process.
C:\iblrig_params\IBL\experiments\_iblrig_misc\setups\flush_water\sessions\201901~1 - The process cannot access the file because it is being used by another process.
```

After clicking 'stop', the 'stop trial' button is greyed out so the only way to stop the flush is to unplug the state machine from USB.

**Comment by anne-urai** [comment]
When only clicking 'stop trial', everything is fine and flush_water exist gracefully.
