### ISSUE TITLE
stopping trainingChoiceWorld crashes python and bonsai

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#87]
When running trainingChoiceWorld, and clicking 'stop' then 'stop trial', python and then bonsai crash

```
INFO:
##########################################
TRIAL NUM:              7
STIM POSITION:          -35
STIM CONTRAST:          1.0
STIM PHASE:             1.1472348048233707
STIM PROB LEFT:         0.5
RESPONSE TIME:          0.9431

TRIAL CORRECT:          False

NTRIALS CORRECT:        5
NTRIALS ERROR:          2
WATER DELIVERED:        15
TIME FROM START:        0:00:40.984055
AMBIENT SENSOR DATA:    not saved - deactivated in task settings
##########################################
------> [MainProcess:_iblrig_tasks_trainingChoiceWorld.py:202] 2019-01-23T16:51:18.984

INFO: Starting trial: 8
------> [MainProcess:_iblrig_tasks_trainingChoiceWorld.py:93] 2019-01-23T16:51:18.985
stderr;2019-01-23 16:51:25.985032;;|Different project data hashes:
8d2e9805c93cd140135a81edc35f41b0fc80831bd3be777f8e14f0c83cfbdafa
7e8ca72dbf00c3d99b20bd351912dad43b94a6c8ec5fdb3f04465f4b69214ae9
|;;
stderr;2019-01-23 16:51:25.985032;;|Run protocol cannot be executed because project is not saved.
|;;
Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\_iblrig_tasks_trainingChoiceWorld.py", line 24, in <module>
    sph = SessionParamHandler(task_settings, user_settings)
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\session_params.py", line 125, in __init__
    self._configure_rotary_encoder(RotaryEncoderModule)
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\session_params.py", line 600, in _configure_rotary_encoder
    m = RotaryEncoderModule(self.COM['ROTARY_ENCODER'])
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\pybpod_rotaryencoder_module\module_api.py", line 27, in __init__
    if serialport: self.open(serialport)
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\pybpod_rotaryencoder_module\module_api.py", line 35, in open
    self.arcom = ArCOM().open(serialport, 115200)
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\pybpodapi\com\arcom.py", line 98, in open
    self.serial_object = serial.Serial(serial_port, baudrate=baudrate, timeout=timeout)
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\serial\serialutil.py", line 240, in __init__
    self.open()
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM4': PermissionError(13, 'Access is denied.', None, 5)
Traceback (most recent call last):
  File "..\..\..\bpod_lights.py", line 38, in <module>
    main(comport, int(command))
  File "..\..\..\bpod_lights.py", line 23, in main
    ser = serial.Serial(port=comport, baudrate=115200, timeout=1)
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\serial\serialutil.py", line 240, in __init__
    self.open()
  File "c:\users\ibl\appdata\local\continuum\anaconda3\envs\iblenv\lib\site-packages\serial\serialwi open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM5': PermissionError(13, 'Access is denied.', None, 5)
C:\iblrig_params\IBL\experiments\_iblrig_tasks\setups\trainingChoiceWorld\sessions\201901~1\20190123-165038.csv - The process cannot access the file because it is being used by another process.
C:\iblrig_params\IBL\experiments\_iblrig_tasks\setups\trainingChoiceWorld\sessions\201901~1 - The process cannot access the file because it is being used by another process.

Unhandled Exception: System.CannotUnloadAppDomainException: Error while unloading appdomain. (Exception from HRESULT: 0x80131015)
   at System.AppDomain.Unload(AppDomain domain)
   at Bonsai.Program.Main(String[] args)
   at Bonsai64.Program.Main(String[] args)
```

**Comment by nbonacchi** [comment]
python crash here is because you ran the task after having stopped too soon... the ports were still disconnecting
The Bonsai crash is expected you should wait for it to happen before running again...

**Comment by anne-urai** [comment]
I don't understand what you mean - I ran the task, and then wanted to stop after 7 trials. Do you mean after the *previous* stop I should wait some minimum amount of time before starting again?
