### ISSUE TITLE
no calibration file was found

### ISSUE THREAD

**Issue by HernandoMV** [int-brain-lab/iblrig#94]
This happened after calibrating the rig, and trying to start the habituation protocol:

```
Looking for calibration of board: _iblrig_MrsicHofer_behavior_009


INFO: PREVIOUS SESSION FOUND
LOADING PARAMETERS FROM: C:\iblrig_data\Subjects\_iblrig_test_mouse\2019-01-09\003\raw_behavior_data\_iblrig_taskData.raw.jsonable

PREVIOUS NTRIALS:              2
PREVIOUS NTRIALS (no repeats): 2
LAST REWARD:                   3.2
LAST GAIN:                     8.0
LAST CONTRAST SET:             [1.0, 0.5]
BUFFERS LR:                    [[[0.0, 0.0, ...

REWARD AMOUNT: 3.3000000000000003
PREVIOUS WEIGHT: 123.0
PREVIOUS WATER DRANK: 3.2


NO CALIBRATION FILE WAS FOUND:
Calibrate the rig or use a manual calibration value.


Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\_iblrig_tasks_trainingChoiceWorld.py", line 20, in <module>
    sph = SessionParamHandler(task_settings, user_settings)
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\session_params.py", line 102, in __init__
    self.REWARD_VALVE_TIME = self._init_reward_valve_time()
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\session_params.py", line 439, in _init_reward_valve_time
    raise ValueError
ValueError
```

**Comment by nbonacchi** [comment]
Calibrate the rig or use a manual calibration value.

Change the task_settings.py variables to match what you want to run with
**C:\iblrig_params/IBL/tasks/<task_name>/task_settings.py**

Also that message if from an older version of the task...
please go to C:\iblrig and run `python update.py 3.5.3` (run this twice please)

**Comment by HernandoMV** [comment]
Yes, it got fixed this afternoon, thanks,
